### ISSUE TITLE
Problem building prover submodule

### ISSUE THREAD

**Issue by jeanqasaur** [ucsd-progsys/liquidhaskell#834] opened 2016-09-23 04:52 UTC
Hi, I'm getting the following issue building the prover submodule (with head at 94912a7, though I also had this problem with head at 9be047). Is there some dependency I'm missing? Thanks!

~/code/liquidhaskell/prover$ cabal install
Resolving dependencies...
Configuring prover-0.1.0.0...
Building prover-0.1.0.0...
Failed to install prover-0.1.0.0
Build log ( /home/jeanyang/.cabal/logs/prover-0.1.0.0.log ):
cabal: Entering directory '.'
Configuring prover-0.1.0.0...
Building prover-0.1.0.0...
Preprocessing library prover-0.1.0.0...
[2 of 8] Compiling Prover.SMTInterface ( src/Prover/SMTInterface.hs, dist/build/Prover/SMTInterface.o )

src/Prover/SMTInterface.hs:9:30: Not in scope: ‘defConfig’
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
prover-0.1.0.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by ranjitjhala** [comment] 2016-09-23 05:41
Hi @jeanqasaur!, 

are you by any chance trying to build _only_ the prover? (Or LH in general, and you get this with prover?) 

If the former -- we'll look into it (though I don't know if we've ever built prover outside of LH... @nikivazou?) 

If the former -- can you try using `stack` (i've found it to be a real godsend in these matters...)

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#build-with-stack-recommended

Specifically, these three steps:

```bash
git clone --recursive git@github.com:ucsd-progsys/liquidhaskell.git
cd liquidhaskell
stack install
```

**Comment by jeanqasaur** [comment] 2016-09-23 14:20
Hi, I ran into a problem with the prover dependency when running "make
test" so then I tried to build prover by itself. I'm running into the same
problem with both cabal and stack, which is that there is some variable
"defConfig" that is not defined. Is "make test" supposed to still work?
Thanks!


--
Jean Yang
website <http://jeanyang.com/> | twitter <http://twitter.com/jeanqasaur>

**Comment by ranjitjhala** [comment] 2016-09-23 14:25
Hmm.

1. Does "stack install" work in the top level directory?
2. Can you then do "stack exec -- liquid tests/pos/Abs.hs"

?

**Comment by jeanqasaur** [comment] 2016-09-23 14:27
Yes, both work and Abs.lhs is safe.


--
Jean Yang
website <http://jeanyang.com/> | twitter <http://twitter.com/jeanqasaur>

**Comment by jeanqasaur** [comment] 2016-09-23 14:29
I'm also able to run the tutorial examples, which makes it confusing that
"make test" should fail...


--
Jean Yang
website <http://jeanyang.com/> | twitter <http://twitter.com/jeanqasaur>

**Comment by ranjitjhala** [comment] 2016-09-23 14:48
Great! Can you also check if the following work:

1. `stack test liquidhaskell` ... to run the full suite (may take a while..)

2. `liquid tests/pos/Abs.hs` ... as `stack install` should have put the
executable `liquid` in your path (assuming you added `~/.local/bin/` to
your $PATH

That should be it.

There's something fishy about the `test` rule in the  Makefile/cabal that
we'll have to fix (perhaps when @gridaphobe and @nikivazou are back from
ICFP as I don't want to break the CI...)

**Comment by jeanqasaur** [comment] 2016-09-23 14:57
Thanks! Yes, liquid seemed to install properly, but I get this error with
"stack test liquidhaskell:"

--  While building package prover-0.1.0.0 using:

/home/jeanyang/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3
--builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 build lib:prover
exe:prover --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to:
/home/jeanyang/code/liquidhaskell/.stack-work/logs/prover-0.1.0.0.log

    Configuring prover-0.1.0.0...
    Preprocessing library prover-0.1.0.0...
    [6 of 8] Compiling Prover.SMTInterface ( src/Prover/SMTInterface.hs,
.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Prover/SMTInterface.o )

    src/Prover/SMTInterface.hs:9:30: Not in scope: ‘defConfig’

--

As expected, here's what's in prover-0.1.0.0.log:

Configuring prover-0.1.0.0...
Preprocessing library prover-0.1.0.0...
[6 of 8] Compiling Prover.SMTInterface ( src/Prover/SMTInterface.hs,
.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Prover/SMTInterface.o )

src/Prover/SMTInterface.hs:9:30: Not in scope: ‘defConfig’




--
Jean Yang
website <http://jeanyang.com/> | twitter <http://twitter.com/jeanqasaur>

**Comment by ranjitjhala** [comment] 2016-09-23 15:14
Yikes...! Ok I'll look into that ASAP!

**Comment by ranjitjhala** [comment] 2016-09-23 18:14
Grr. Can't reproduce this; a fresh clone seems to do 

```
$ git clone --recursive https://github.com/ucsd-progsys/liquidhaskell.git lh-test 
$ cd lh-test
$ stack build
$ stack test
```

@jeanqasaur can you try a fresh sequence? Could the earlier use of cabal have caused some wierdness?

**Comment by jeanqasaur** [comment] 2016-09-23 21:40
Yes, that works--thanks! What is lh-test?


--
Jean Yang
website <http://jeanyang.com/> | twitter <http://twitter.com/jeanqasaur>

**Comment by ranjitjhala** [comment] 2016-09-23 22:59
Oh LH-test was just a random directory name I made up for the fresh clone...

**Comment by nikivazou** [comment] 2016-09-26 21:17
@jeanqasaur it worked right? I am closing the issue!

**Comment by jeanqasaur** [comment] 2016-09-26 21:18
Yes, thanks for all the help!


--
Jean Yang
website <http://jeanyang.com/> | twitter <http://twitter.com/jeanqasaur>

**Closed by nikivazou** 2016-09-26 21:17 UTC
