### ISSUE TITLE
Add stitch-lh to the suite of benchmarks

### ISSUE THREAD

**Issue by facundominguez** [ucsd-progsys/liquidhaskell#1933] opened 2022-02-13 00:36 UTC
Now that stich-lh seems to be building again with the fixes for #1912, perhaps it is a good time to consider adding it to the benchmark (or maybe Macro?) suite. This would prevent accidental breakage of a moderately interesting use case of LH.

The code takes near 1 minute to verify, and the longest modules take between 20 and 30 seconds, which perhaps it is acceptable to run on every PR.

I'm asking here ahead of making the change in case someone has a better idea.

**Comment by ranjitjhala** [comment] 2022-02-13 01:15
This would be awesome, thanks!

**Comment by nikivazou** [comment] 2022-02-14 09:50
I agree too to add it in the benchmark suite to prevent accidental breakage, but I do have a "better idea". 

The problem is that when someone `clones` liquidhaskell now, they also clone all our macro benchmarks, which is a lot. 
Is it possible to make circle check the stich-lh benchmark without putting the code in the repo?

My plan was to move all the macro benchmarks in https://github.com/liquidhaskell/ and remove them from the current repo (but never made it :). If you know how to check stich-lh on the cloud without actually putting it in the repo, then we can also remove the other big benchmarks! 

Of course, if it is too complicated, just add it in the repo.

**Comment by facundominguez** [comment] 2022-02-14 11:59
> Is it possible to make circle check the stich-lh benchmark without putting the code in the repo?

I think we can make that work. We would need to create a new repo to hold the existing benchmarks and link to stitch-lh in CI. Thanks for your thoughts.

**Comment by Fizzixnerd** [comment] 2022-02-14 13:51
I'm thinking this sounds like a job for `git` submodules, the issue being that we already need to clone recursively to setup `liquid-fixpoint`.  This can be hacked around by (for example) having circle clone the macros as just a separate repo (thus not using submodules!), or by doing shenanigans with `cherry-pick` in the a circle run itself, to only add the submodule in the CI runs.

EDIT: It is also possible to just change the instructions on how to build liquidhaskell to say which submodules to update depending on your use-case, I suppose.

I think having a number of goals would be good so that we don't screw up the workflow that we currently have, and help ensure this feature remains maintainable.  Here are my two cents:

1. **It is necessary to have a workflow whereby previous circle pipelines do not break if we need to rerun them.**  This precludes always pulling a specific branch (i.e. `main`) for the benchmarks repo, since if the changes to the benches are dependent on the version of liquid used, this would break *old* pipelines when they try to pull the *new* macro code from the same branch name.
2. **It is necessary to also have a mechanism to warn when the latest version differs from the one being pulled,** however, to help prevent forgetting to update the circle CI config or wherever the hash for the commit to grab is being stored.  This should print a loud warning at the start and end of the CI in a scary colour to help ensure it isn't missed, but won't fail the CI (thus not screwing up 1. above)
3. **It should be easy to add additional projects (that have annotated their sources) as benchmarks.**  To this end, I think it would be best to add stitch-lh as a git submodule of the macro benchmarks, rather than linking to `stitch-lh` directly in the CI.  This implicitly pins the version pulled of stitch-lh as well (without requiring a bunch of hashes in the CI itself), which is nice since it means upstream changes to a project cannot break our CI, while we are free to pull in changes easily as a simple commit to the macro-benchmarks repo and just update the one macro benchmarks hash in the CI, as usual.

**Comment by nikivazou** [comment] 2022-02-14 14:02
Not that liquid-fixpoint is special, in that building liquidhaskell depends on building liquid-fixpoint. 
Indeed liquid-fixpoint could be used as a library, but it is quite common that we make edits in liquid-fixpoint and need to directly link them in liquidhaskell. 

Ideally we do not want downloading or builing liquidhaskell to depend on any of the benchmarks, but we want that the cloud checks pass only when all benchmarks are ok.

**Comment by Fizzixnerd** [comment] 2022-02-14 14:10
> Ideally we do not want downloading or builing liquidhaskell to depend on any of the benchmarks, but we want that the cloud checks pass only when all benchmarks are ok.

Yes, so I think the simplest solution is to store the hash of the benchmarks you want to pull in a config file (either inside the circle config directly, or in just a labelled textfile, not sure if you have a preference)

**Comment by Fizzixnerd** [comment] 2022-02-15 15:19
@facundominguez had a better idea which I have begun to implement.  The basic idea is that instead of modifying stitch-lh, just add it as a dependency of liquidhaskell in stack.  From the [stack docs](https://docs.haskellstack.org/en/stable/yaml_configuration/#:~:text=Project%20packages%20will%20be%20built%20by%20default%20with%20a%20stack%20build%20without%20specific%20targets.%20Dependencies%20will%20only%20be%20built%20if%20they%20are%20depended%20upon.):

```
- Project packages will be built by default with a stack build without specific targets.
  Dependencies will only be built if they are depended upon.
```

To this end, I propose a two part solution: part 1 is just adding stitch-lh as an extra-dep and ensuring it is built in the CI.  Part 2 is spinning off the rest of the benchmarks into a package and doing the same thing.

**Comment by ranjitjhala** [comment] 2022-02-15 16:03
Adding it directly to the LH repository has the benefit that we can also
track it as part of our own performance aggressions. That could be quite
valuable.

**Comment by facundominguez** [comment] 2022-02-15 18:39
> ... track it as part of our own performance aggressions.

I like "performance aggressions". :) 

If benchmarks are moved to a separate repository, we can integrate the `stitch-lh` code there and have it measured as part of running the benchmarks. This still would address Niki's request, I think.

**Comment by facundominguez** [comment] 2022-02-22 02:59
> The problem is that when someone clones liquidhaskell now, they also clone all our macro benchmarks, which is a lot.

@nikivazou, one question came up to me recently. Why would someone clone LH, yet not want to get all the code there is to test it?

I imagine splitting the repository might help reducing downloads during cloning, but if we wanted to optimize this, we could instead suggest doing shallow clones.

I'm asking because splitting the repository has a cost too. By now we are familiar with the work involved in keeping LH and liquid-fixpoint repos in sync. Recently we had rest-rewrite added as another repo. Aren't we most of the time interested in merging changes to these repos only when there is confidence that LH tests are still passing? Splitting would make this harder to determine. If we were optimizing for this, I'd expect we would go in the opposite direction and have some form of monorepo.

**Comment by nikivazou** [comment] 2022-02-22 10:20
My answer is because as a user someone wants to build liquid haskell with minimum resources (compile time and storage space). I agree that as developers we prefer the benchmarks to be in the same place. 

Thinking again, after reading your comments, it would be ok to have the benchmarks here, if we assume that the users are not going to clone but install LH from hackage.


(But, @facundominguez I think you have much more experience with these than me and splitting was a suggestion. If you believe it will be much more trouble than gain, I am totally ok with keeping everything in the same repo.)

**Comment by facundominguez** [comment] 2022-02-25 18:50
It looks to me like the most convenient would be to include `stitch-lh` in LH directly then.

The concerns of making LH manageable to all users are valid, still. I'd expect that the storage requirements become the largest only when all the tests are built. To show the differences,
 * `.git` takes near 120 MB
 *  `.stack-work` takes near 500 MB
 *  `tests` takes near 10 MB
Only storing source code should modestly increase `tests` and `.git`.

**Comment by nikivazou** [comment] 2022-03-07 17:32
Seems that #1946 adds it directly (which I am totally fine with!). Closing this!

**Closed as completed by nikivazou** 2022-03-07 17:32 UTC
