### ISSUE TITLE
`import qualified` multiple modules under the same name confuses LH

### ISSUE THREAD

**Issue by spacekitteh** [ucsd-progsys/liquidhaskell#1534] opened 2019-07-26 03:19 UTC
So, I have
```haskell
import qualified Data.Vector as V (Vector)
import qualified Data.Vector.Generic as V hiding (Vector)
```

I then try to use a `V.Vector` and I get this error:

```
liquid.EXE: C:\Users\sophi\code\liquidhaskell\.stack-work\install\a4c83508\share\x86_64-windows-ghc-8.6.5\liquidhaskell-0.8.6.0\include\Data\Vector.spec:(12,16)-(14,0): Error: Specified type does not refine Haskell type for `Data.Vector.Generic.!` (Plugged Init types new)
The Liquid type

    forall a . (Data.Vector.Vector a) -> GHC.Types.Int -> a

is inconsistent with the Haskell type

    forall (v :: * -> *) a.
Data.Vector.Generic.Base.Vector v a =>
v a -> GHC.Types.Int -> a

defined at <no location info>

Specifically, the Liquid component

    (Data.Vector.Vector a)

is inconsistent with the Haskell component

    v a


HINT: Use the hole '_' instead of the mismatched component (in the Liquid specification)
```

**Comment by ranjitjhala** [comment] 2019-07-26 04:30
Hmm, what was the LH spec you wrote that triggered this error? (can you
e.g. make a gist?)

thanks!

**Comment by spacekitteh** [comment] 2019-07-26 06:04
I hadn't written anything yet, that's the thing. It was just vanilla Haskell.

**Comment by ranjitjhala** [comment] 2019-07-26 06:28
Oh that’s nasty! It was for the spec for

 !

Thanks for pointing that out!

**Comment by spacekitteh** [comment] 2019-07-26 07:31
It actually happens for every item in the spec, but it seems to parse it out of order.

**Comment by ranjitjhala** [comment] 2019-07-26 14:19
So your code is just the imports above plus some use of !

If not can you paste a minimal reproducing snippet? Thanks!!

**Comment by facundominguez** [comment] 2024-06-01 00:12
Since only putting the imports in a file doesn't cause a failure, I'm closing the issue for now. But please, feel free to reopen if this is still failing with the latest LH.

**Closed as completed by facundominguez** 2024-06-01 00:12 UTC
