### ISSUE TITLE
PLE fails with local let binder?

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1204] opened 2017-12-19 19:11 UTC
In the below, why does `propOK` work but `propBAD` fail? The only difference is the intermediate let-binder `m`? 

```haskell
{-@ LIQUID "--exact-data-con" @-}
{-@ LIQUID "--higherorder"    @-}
{-@ LIQUID "--ple"            @-}

module Maps where

import Language.Haskell.Liquid.NewProofCombinators

data Id = Id Int
          deriving (Eq)

data TotalMap a = TM
  { tmDef  :: a
  , tmVals :: [(Id, a)]
  }

{-@ reflect t_empty @-}
t_empty :: a -> TotalMap a
t_empty v = TM v []

{-@ reflect t_update @-}
t_update :: TotalMap a -> Id -> a -> TotalMap a
t_update (TM d kvs) k v = TM d ((k, v) : kvs)

{-@ reflect t_read @-}
t_read :: TotalMap a -> Id -> a
t_read (TM d kvs) key = lookupDefault d key kvs

{-@ reflect lookupDefault @-}
lookupDefault :: (Eq k) => v -> k -> [(k, v)] -> v
lookupDefault d key ((k,v) : kvs)
  | k == key                      = v
  | otherwise                     = lookupDefault d key kvs
lookupDefault d _   []            = d

{-@ reflect exMap @-}
exMap :: TotalMap Int
exMap = t_update (t_update (TM 99 []) (Id 10) 1) (Id 20) 2

{-@ propOK :: () -> TT @-}
propOK () = t_read exMap (Id 50) == 99
         && t_read exMap (Id 10) == 1
         && t_read exMap (Id 20) == 2

{-@ propBAD :: () -> TT @-}
propBAD () = t_read m     (Id 50) == 99       -- WHY DOES THIS FAIL?!
  where
    m = exMap
```

**Comment by facundominguez** [comment] 2024-06-14 18:32
Closing since I cannot reproduce the failure of `propBAD` in the latest LH.

**Closed as completed by facundominguez** 2024-06-14 18:32 UTC
Labels: bug, pbe
