### ISSUE TITLE
Test suite failures when building from Hackage tarball

### ISSUE THREAD

**Issue by peti** [ucsd-progsys/liquidhaskell#1038] opened 2017-05-26 20:00 UTC
I'm seeing the following test suite failures while trying to build liquidhaskell from Hackage via Nix. Is it possible that those tests just won't work unless they are run in a checked-out copy of the Git repository?

~~~
      ReflectClient0.hs:          FAIL (0.48s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 2
      ReflectClient1.hs:          FAIL (0.49s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 2
      ReflectClient2.hs:          FAIL (0.48s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 2
      ReflectClient3.hs:          FAIL (0.56s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 2
      ReflectClient4.hs:          FAIL (0.58s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 2
[...]
fatal: Not a git repository (or any parent up to mount point /tmp)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
test: readCreateProcess: git "show" "--format=\"%d\"" "--quiet" (exit 128): failed
Test suite test: FAIL
~~~

**Comment by nikivazou** [comment] 2017-05-28 02:41
Thanks @peti! 
I do not have access to Nix to reproduce the error. Can you run Liquid Haskell on files other than the above? 

If these are the only failing tests I will blame @ranjitjhala  since he was recently experimenting with these files.

**Comment by ranjitjhala** [comment] 2017-05-28 03:26
Yes these files should work with the latest develop on github... (but
probably not older versions...)

**Comment by peti** [comment] 2017-05-28 08:40
> If these are the only failing tests I will blame @ranjitjhala since he
> was recently experimenting with these files.

Yes, these tests are the only ones failing (because they rely on the Git
repository to be present). All other tests succeed fine. Note that this
issue is not specific to Nix. Everyone running the tests outside of a
Git checkout (i.e. from a release tarball) is going to have that
problem.

**Comment by ranjitjhala** [comment] 2017-05-28 14:36
Hmm. This is puzzling,
you're saying they
require the git
repository to
be present?

(I had meant that
they ought to work
LH as long as it was
the recent stuff.)

I guess we can reproduce
this by doing a `stack sdist`
and then using the generated tarball?

**Comment by peti** [comment] 2017-05-28 15:20
> I guess we can reproduce this by doing a `stack sdist` and then using the generated tarball?

I don't know about the current state of the Github repository. I'm using the latest release version from <http://hackage.haskell.org/package/liquidhaskell-0.8.0.0/liquidhaskell-0.8.0.0.tar.gz>.

But yes, if you try to run "cabal test" in an extracted copy of the release tarball, then it should fail.

**Comment by peti** [comment] 2017-08-19 19:37
I figured I'd try again whether the situation has maybe improved with the current 0.8.0.1 release, but unfortunately the test suite still fails with exactly the same issue -- both inside and outside of Nix builds. To reproduce this, simply run:

~~~
$ cabal get liquidhaskell
$ cd liquidhaskell-0.8.0.1
$ cabal sandbox init
$ cabal install --only-dependencies
$ cabal test
[...]
      Mismatch.hs:                OK (0.50s)
      MultipleRecordSelectors.hs: OK (0.51s)
      num-float-error.hs:         OK (0.50s)
      num-float-error1.hs:        OK (0.50s)
      predparams.hs:              OK (0.48s)
      Qualif.hs:                  OK (0.51s)
      RClass.hs:                  OK (0.36s)
      SizeFunMissing.hs:          OK (0.51s)
      T649.hs:                    OK (0.52s)
      T691.hs:                    OK (0.36s)
      T773.hs:                    OK (0.50s)
      T774.hs:                    OK (0.50s)
      typeAliasDup.hs:            OK (0.55s)
      Unbound.hs:                 OK (0.36s)
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
test: readCreateProcess: git "show" "--format=\"%d\"" "--quiet" (exit 128): failed
Test suite test: FAIL
Test suite logged to: dist/test/liquidhaskell-0.8.0.1-test.log
Test suite liquidhaskell-parser: RUNNING...
Test suite liquidhaskell-parser: PASS
Test suite logged to: dist/test/liquidhaskell-0.8.0.1-liquidhaskell-parser.log
1 of 2 test suites (1 of 2 test cases) passed.
~~~

**Comment by ranjitjhala** [comment] 2017-08-21 17:29
Many thanks for the reminder @peti -- I will try to get to this as soon as I am done with an in-flight refactoring (which should be very soon!)

**Comment by ranjitjhala** [comment] 2017-08-24 18:48
Hi @peti -- ok, looks like the issue is that the code that generates the "logs" from the regression tests uses the git hash. I have modified it, so that it just uses a `"plain"` instead of the git hash if being run outside a git tree. Can you try again with this tarball:

```
wget http://goto.ucsd.edu/~rjhala/liquidhaskell-0.8.0.2.tar.gz
```

Its been a long time since I used plain cabal and now I get this bizarre error while 
following your steps above (perhaps cabal etc are super stale on my machine?)

```
rjhala@borscht ~/t/liquidhaskell-0.8.0.2> cabal install --only-dependencies
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: liquidhaskell-0.8.0.2 (user goal)
trying: binary-0.7.5.0/installed-b4f... (dependency of liquidhaskell-0.8.0.2)
next goal: ghc-boot (dependency of liquidhaskell-0.8.0.2)
rejecting: ghc-boot-8.2.1 (conflict: liquidhaskell => ghc-boot==8.0.2)
rejecting: ghc-boot-8.0.2 (conflict: binary==0.7.5.0/installed-b4f...,
ghc-boot => binary==0.8.*)
rejecting: ghc-boot-8.0.1 (conflict: liquidhaskell => ghc-boot==8.0.2)
Dependency tree exhaustively searched.
```

In the meantime, I am also updating my cabal to see if the above works.

**Comment by ranjitjhala** [comment] 2017-08-24 20:25
hmm @gridaphobe any idea what's going on above?

**Comment by gridaphobe** [comment] 2017-08-24 20:26
looks like you might have the wrong version of ghc installed? what does `ghc --version` say?

**Comment by ranjitjhala** [comment] 2017-08-24 20:32
ah of course!

```
The Glorious Glasgow Haskell Compilation System, version 7.10.2
```

yikes... guess  I'd forgotten how much `stack` handles! 

How _does_ one install GHC 8 without stack?

**Comment by gridaphobe** [comment] 2017-08-24 20:36
homebrew? but it's on 8.2 now...

if you can find the path to stack's ghc (`stack exec -- which ghc` ?) you can run `cabal -w /path/to/ghc do_this` to use a different ghc

**Comment by ranjitjhala** [comment] 2017-08-24 20:38
ooh, nice. that got it unstuck...

**Comment by ranjitjhala** [comment] 2017-08-25 05:58
Can't for the life of me get the tests that depend on `vector` or `LiquidHaskell` 
to work with `cabal test` ... ?!

Any idea where I need to add the dependencies?

      vector00.hs:                FAIL (0.11s)
      BinarySearchOverflow.hs:    FAIL (0.10s)

Has been working smoothly with `stack test` so am quite at a loss.

**Comment by ranjitjhala** [comment] 2017-12-05 21:20
Hey this is fixed now right? [please reopen]

**Closed by ranjitjhala** 2017-12-05 21:20 UTC

**Comment by ulysses4ever** [comment] 2025-08-13 19:48
With the latest release of liquid-fixpoint (0.9.6.3.3), something is still trying to find git repository

```
      qualif-inst.fq:         OK (0.02s)
      ebind-06.fq:            OK (0.02s)
      poly.fq:                OK (0.02s)
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Test suite test: FAIL
Test suite logged to:
/home/artem/tmp/liquid-fixpoint-0.9.6.3.3/./dist-newstyle/build/x86_64-linux/ghc-9.8.4/liquid-fixpoint-0.9.6.3.3/t/test/test/liquid-fixpont-0.9.6.3.3-test.log
0 of 1 test suites (0 of 1 test cases) passed.
Error: [Cabal-7125]
Tests failed for test:test from liquid-fixpoint-0.9.6.3.3.

HasCallStack backtrace:
  collectBacktraces, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:169:13 in ghc-internal:GHC.Internal.Exception
  toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/Internal/IO.hs:260:11 in ghc-internal:GHC.Internal.IO
  throwIO, called at src/Distribution/Simple/Utils.hs:445:3 in Cabal-3.17.0.0-inplace:Distribution.Simple.Utils
  dieWithException, called at src/Distribution/Client/ProjectOrchestration.hs:1380:21 in cabal-install-3.17.0.0-inplace:Distribution.Cliet.ProjectOrchestration

```

can someone reproduce it?

I'm also seeing one test failing:

```
      maps02.fq:              

Liquid-Fixpoint Copyright 2013-21 Regents of the University of California.
All Rights Reserved.

Crash!: :1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "Term of kind `STORE_ALL` not supported in default mode, try `--arrays-exp`."
CRASH: -1

      maps02.fq:              FAIL (0.02s)
        tests/test.hs:170:
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
        Use -p '/cvc5-pos.maps02.fq/' to rerun this test only.

```

**Comment by facundominguez** [comment] 2025-08-14 12:38
There are a bunch of calls that depend on being on a git repo to succeed here [[link]](https://github.com/ucsd-progsys/liquid-fixpoint/blob/324215f209d87fcef50fded4362b36fee38d2b3b/tests/test.hs#L307). I think it would make sense to remove the code that needs them (the `loggingTestReporter`).

I can reproduce the failures with
```
nix-shell -p haskell.compiler.ghc9122 cabal-install z3 cvc5 --run "cabal unpack liquid-fixpoint"
cd liquid-fixpoint-0.9.6.3.3
nix-shell -p haskell.compiler.ghc9122 cabal-install z3 cvc5 --run "cabal test"
```

The cvc5 failure is perhaps sensitive to the cvc5 version in use.

**Comment by ulysses4ever** [comment] 2025-08-14 14:46
I see, thanks for confirming! Maybe we should reopen the issue or create a new one so that it's tracked.

**Comment by facundominguez** [comment] 2025-08-14 16:03
I created https://github.com/ucsd-progsys/liquid-fixpoint/issues/760.
