### ISSUE TITLE
liquid breaks when using NoImplicitPrelude

### ISSUE THREAD

**Issue by bonds** [ucsd-progsys/liquidhaskell#1224] opened 2018-01-19 19:40 UTC
I'm getting an error from liquid about its own code, instead of about the code I wrote...at least, that's the way it looks:

````
~ ❯❯❯ stack exec -- liquid ~/bin/play.hs                               Fri 2018-01-19 11:37:07 -0800
LiquidHaskell v0.8.2.2 Copyright 2013-17 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************


**** DONE:  annotate ***********************************************************


**** RESULT: ERROR *************************************************************


 /home/scott/.stack/global-project/.stack-work/install/x86_64-openbsd-maj6-min2/lts-10.3/8.2.2/share/x86_64-openbsd-ghc-8.2.2/liquidhaskell-0.8.2.2/include/Data/ByteString/Lazy.spec:5:9-13: Error: Illegal type specification for `measure bllen`

 5 | measure bllen :: Data.ByteString.Lazy.ByteString -> { n : Data.Int.Int64 | 0 <= n }
             ^^^^^

     measure bllen :: ByteString -> {n : Int64 | 0 <= n}
     Sort Error in Refinement: {n : GHC.Int.Int64 | 0 <= n}
     The sort GHC.Int.Int64 is not numeric
  because
The sort GHC.Int.Int64 is not numeric


 /home/scott/.stack/global-project/.stack-work/install/x86_64-openbsd-maj6-min2/lts-10.3/8.2.2/share/x86_64-openbsd-ghc-8.2.2/liquidhaskell-0.8.2.2/include/Data/ByteString/Lazy.spec:7:11: Error: Bad Invariant Specification
     invariant  {bs : ByteString | 0 <= bllen bs}
     Sort Error in Refinement: {bs : Data.ByteString.Lazy.Internal.ByteString | 0 <= bllen bs}
     The sort GHC.Int.Int64 is not numeric
  because
The sort GHC.Int.Int64 is not numeric


 /home/scott/.stack/global-project/.stack-work/install/x86_64-openbsd-maj6-min2/lts-10.3/8.2.2/share/x86_64-openbsd-ghc-8.2.2/liquidhaskell-0.8.2.2/include/Data/ByteString/Lazy.spec:9:11: Error: Bad Invariant Specification
     invariant  {bs : ByteString | bllen bs == stringlen bs}
     Sort Error in Refinement: {bs : Data.ByteString.Lazy.Internal.ByteString | bllen bs == stringlen bs}
     Cannot unify GHC.Int.Int64 with GHC.Types.Int in expression: bllen bs == stringlen bs
  because
Invalid Relation bllen bs == stringlen bs with operand types GHC.Int.Int64 and GHC.Types.Int


 /home/scott/.stack/global-project/.stack-work/install/x86_64-openbsd-maj6-min2/lts-10.3/8.2.2/share/x86_64-openbsd-ghc-8.2.2/liquidhaskell-0.8.2.2/include/Data/ByteString/Lazy.spec:(25,8)-(28,0): Error: Illegal type specification for `assumed type Data.ByteString.Lazy.fromStrict`

 25 |     :: i : Data.ByteString.ByteString
 26 |     -> { o : Data.ByteString.Lazy.ByteString | bllen o == bslen i }
 27 |
 28 | assume toStrict

     assumed type Data.ByteString.Lazy.fromStrict :: i:ByteString -> {o : ByteString | bllen o == bslen i}
     Sort Error in Refinement: {o : Data.ByteString.Lazy.Internal.ByteString | bllen o == bslen i}
     Unbound Symbol bslen
 Perhaps you meant: bllen


 /home/scott/.stack/global-project/.stack-work/install/x86_64-openbsd-maj6-min2/lts-10.3/8.2.2/share/x86_64-openbsd-ghc-8.2.2/liquidhaskell-0.8.2.2/include/Data/String.spec:(6,9)-(9,0): Error: Illegal type specification for `class method Data.String.fromString`

 6 |     ::  forall a. Data.String.IsString a
 7 |     =>  i : [GHC.Types.Char]
 8 |     ->  { o : a | len i == stringlen o }

     class method Data.String.fromString :: (IsString a) =>
                                            i:[Char] -> {VV : a | len i == stringlen VV}
     Sort Error in Refinement: {VV : a_agLF | len i == stringlen VV}
     Unbound Symbol len
 Perhaps you meant: bllen


 LH.Bare.listTyDataCons:0:0: Error: Illegal data refinement for `[]`
     Size function len x should have type int.
     Unbound Symbol len
 Perhaps you meant: bllen

~  [2] ❯❯❯ liquid --version                                                 Fri 2018-01-19 11:37:12 -0800
LiquidHaskell v0.8.2.2 Copyright 2013-17 Regents of the University of California. All Rights Reserved.
````

**Comment by nikivazou** [comment] 2018-01-19 19:44
Did you install Liquid Haskell from git source or cabal? 

This error should not happen, looks like it is not using the proper fixpoint version.

**Comment by bonds** [comment] 2018-01-19 19:47
I installed using ````stack install liquidhaskell```` and the stack solver told me to add some extra dependencies:

extra-deps:
- liquid-fixpoint-0.7.0.6 # for liquidhaskell
- located-base-0.1.1.1 # for liquidhaskell
- dotgen-0.4.2 # for liquidhaskell
- fgl-visualize-0.1.0.1 # for liquidhaskell

**Comment by ranjitjhala** [comment] 2018-01-19 19:51
Another possibility: your `Play.hs` file is not importing (i.e. hiding)
`Prelude`?

@nikivazou the problem is that for some reason the `include/GHC/Int.spec`
is not being loaded,

and so specifically, LH is missing the fact that:

   embed GHC.Int.Int64 as int

Scott can you show us the contents of `Play.hs`?

**Comment by ranjitjhala** [comment] 2018-01-19 19:53
but the `unbound symbol 'len'` makes me think you're
hiding Prelude, which, unfortunately is a big hassle
for LH.

(@niki we should make this an issue and see if there
 is some way to solve it; there are lots of odd
 dependencies on the standard prelude...)

**Comment by bonds** [comment] 2018-01-19 23:06
@ranjitjhala I can repro this when play.hs is cut down to just this:

````
#!/usr/bin/env stack
{- stack
  --install-ghc
  runghc
  --package protolude
-}
-- vim:ft=haskell:

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE NoImplicitPrelude #-}

module Main where

import Protolude
import Data.ByteString.Lazy

main = print "hello, world"
````
If I cut out the import Protolude line, liquid works fine. If I cut out the NoImplicitPrelude line, liquid work fine. If I cut out the import Data.ByteString.Lazy, liquid works fine. But if all three are there, I get the errors mentioned at the top of this ticket.

**Comment by bonds** [comment] 2018-01-19 23:16
Well, that's not entirely right, I get different errors when removing those lines. If I remove Data.ByteString.Lazy I get:
````
~/tmp ❯❯❯ stack exec -- liquid play.hs                                      Fri 2018-01-19 15:10:51 -0800
LiquidHaskell v0.8.2.2 Copyright 2013-17 Regents of the University of California. All Rights Reserved.


**** DONE:  A-Normalization ****************************************************


**** DONE:  annotate ***********************************************************


**** RESULT: ERROR *************************************************************


 LH.Bare.listTyDataCons:0:0: Error: Illegal data refinement for `[]`
     Size function len x should have type int.
     Unbound Symbol len
 Perhaps you meant: head, x
````
If I remove NoImplicitPrelude I get:
````
Invalid Source


 /home/scott/tmp/play.hs:17:8-12: Error: GHC Error

 17 | main = print "hello, world"
             ^^^^^


         Ambiguous occurrence ‘print’
It could refer to either ‘print’,
                         imported from ‘Prelude’ at /home/scott/tmp/play.hs:12:8-11
                         (and originally defined in ‘System.IO’)
                      or ‘print’,
                         imported from ‘Protolude’ at /home/scott/tmp/play.hs:14:1-16
````
If I remove import Protolude I get:
````
~/tmp ❯❯❯ stack exec -- liquid play.hs                                      Fri 2018-01-19 15:12:39 -0800
LiquidHaskell v0.8.2.2 Copyright 2013-17 Regents of the University of California. All Rights Reserved.


**** DONE:  annotate ***********************************************************


**** RESULT: ERROR *************************************************************


Invalid Source


 /home/scott/tmp/play.hs:17:8-12: Error: GHC Error

 17 | main = print "hello, world"
             ^^^^^


         Variable not in scope: print :: [Char] -> t
````
That first one looks like something might be amiss with liquid, the second and third look like the normal, expected errors about bugs in my (example) code.

**Comment by ranjitjhala** [comment] 2018-01-22 18:23
The issue is the `{-# LANGUAGE NoImplicitPrelude #-}` I'm afraid...

We'll have to figure out how to engineer stuff to allow it...

(The others are indeed just regular name resolution things that can be fixed by qualifying imports etc...)

**Comment by bonds** [comment] 2018-01-22 18:48
Got it. Looks like this was discussed in #770, should I close this ticket as a dup?

**Comment by ranjitjhala** [comment] 2018-01-22 18:56
Oh, thanks for finding that -- yes duplicate indeed, will close this one. Many thanks @bonds will keep you posted as we figure this out!

**Closed as completed by ranjitjhala** 2018-01-22 18:56 UTC
Labels: modules
