### ISSUE TITLE
Cannot reflect functions that return functions

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1380] opened 2018-11-30 23:26 UTC
LH barfs when given the below:

```haskell
{-@ LIQUID "--reflection" @-}

type Silly = () -> Int

{-@ reflect fincr @-}
fincr :: Silly -> Silly
fincr f () = 1 + f ()

{-@ reflect barf @-}
barf :: Silly -> Silly
barf f = fincr f
```

The complaint: 

```

 /Users/rjhala/research/stack/liquidhaskell/tests/todo/Silly.hs:9:13-15: Error: Illegal type specification for `Main.boo`

 9 | {-@ reflect boo @-}
                 ^^^

     Main.boo :: lq1:(()
                      -> GHC.Types.Int)
                 -> lq2:()
                    -> {VV : GHC.Types.Int | VV == boo lq1 lq2
                                             && VV == fincr lq1}
     Sort Error in Refinement: {VV : int | (VV == Main.boo lq1 lq2
                                            && VV == Main.fincr lq1)}
     The sort func(0 , [Tuple; int]) is not numeric
  because
Cannot unify int with func(0 , [Tuple; int]) in expression: VV == Main.fincr lq1
  because
Invalid Relation VV == Main.fincr lq1 with operand types int and func(0 , [Tuple; int])
```

Essentially it is strengthening the `Int` not the `() -> Int` 

Not clear how to fix this, since our heuristic is to strengthen the "rightmost" type... 

One can "box" the function in a new datatype but that is a bit clunky.

**Comment by nikivazou** [comment] 2018-12-01 08:42
Yes.... LH does not like partially applied functions... You can edit the definition of `barf` to be fully applied

```
barf f x = fincr f x
```

Also, do not box functions!!! 
By experience, if you hide functions is data types, the LH performance gets terrible.... 
I did not have the chance to look into why, but the hack I have been using is instead of defining 

```
data Foo a b = Foo (a -> b)
```

to fake it as 
```
data Foo a b = Foo (Func a b)
data Func a b = Func b [(a,b)]

{-@ reflect apply @-}
apply :: Func a b -> a -> b
apply f x = ... -- lookup with default x in f 
```

**Comment by ranjitjhala** [comment] 2018-12-01 15:07
Hmm good to know about boxing. I did do it and everything DID get very
slow. Puzzling! Let me try your “fully applied” approach.

**Comment by ranjitjhala** [comment] 2018-12-01 22:58
@nikivazou your approach is indeed *much* faster, wonder why boxing functions is so terrible.

On the other hand, you get tedious stuff like this where you have to use "function-equality" to prove trivial things that PLE _should_ do otherwise...

```haskell
{-@ assume axiom_fun_eq :: f:_ -> g:_ -> (x:_ -> { f x = g x}) -> { f = g } @-}
axiom_fun_eq :: (a -> b) -> (a -> b) -> (a -> Proof) -> Proof 
axiom_fun_eq _ _ _ = () 

{-@ reflect adder @-}
adder :: Int -> Int -> Int -> Int 
adder x y z = x + y + z 

{-@ ple lemma_adder @-}
{-@ lemma_adder :: () -> { adder 1 2  = adder 2 1 } @-}
lemma_adder :: () -> ()
lemma_adder _ = axiom_fun_eq (adder 1 2) (adder 2 1) (\_ -> ()) -- this is silly; should be automatic with PLE...
```

**Comment by Mossaka** [comment] 2019-02-19 22:13
I have encountered the same issue as discussed here. The following code gives an illegal type specification error. 

```haskell
type Total_map a = Key -> a

{-@ reflect t_empty @-}
t_empty :: a -> Total_map a
t_empty v = \k -> v

{-@ reflect empty_map @-}
empty_map base = t_empty base
```

The reason for that is empty_map returns a `Total_Map`, which is a partial function. Rose showed me to rewrite the `empty_map` function to the following works. 

```haskell
{-@ reflect empty_map @-}
empty_map base = \k -> t_empty base k
```

Posting here because this might be a motivating example.

**Comment by facundominguez** [comment] 2024-06-02 21:51
Closing since I cannot reproduce the error in the latest LH. But please feel free to reopen if you find similar examples that still fail.

**Closed as completed by facundominguez** 2024-06-02 21:51 UTC
Labels: bug, core-to-logic
