### ISSUE TITLE
Refined GADTs

### ISSUE THREAD

**Issue by bolt12** [ucsd-progsys/liquidhaskell#1633] opened 2020-03-27 14:56 UTC
Hi,

I saw #818 but I'm still having trouble refining a GADT. Here's an example:

```haskell
data Relation a b where
  Empty :: Relation Void Void
  One :: Int -> Relation () ()
  Join :: Relation a r -> Relation b r -> Relation (Either a b) r
  Fork :: Relation c a -> Relation c b -> Relation c (Either a b)

{-@
data Relation a b where
  Empty :: Relation Void Void
  One :: {v:Int | v = 0 || v = 1} -> Relation () ()
  Join :: Relation a r -> Relation b r -> Relation (Either a b) r
  Fork :: Relation c a -> Relation c b -> Relation c (Either a b)
@-}
```

This is what I'd like to do but when I run LH I have the following error: 

```
19 |   One :: {v:Int | v = 0 || v = 1} -> Relation () ()
^

unexpected 'O'
expecting space, "->", "~>", "=>", white space, "|" or end of input
```

Seeing this I change my code to the following:

```haskell
{-@
data Relation a b where
  Empty :: Relation Void Void
  | One :: {v:Int | v = 0 || v = 1} -> Relation () ()
  | Join :: Relation a r -> Relation b r -> Relation (Either a b) r
  | Fork :: Relation c a -> Relation c b -> Relation c (Either a b)
@-}
```

But I get the following erro: 

```
Error: Bad Data Specification

17 | data Relation a b where
^^^^^^^^^


GHC and Liquid specifications have different numbers of type variables for `Relation.Fork`
```

I tried to do as suggested in #818 but I didn't work. I tried looking in other closed issues but couldn't find a solution to my problem, I'm sorry if this has already been answered!

EDIT: Also is it possible in the future to support measures with more than two fields? Would that even make sense?

**Comment by ranjitjhala** [comment] 2020-03-27 17:10
Hmm, thanks for filing this! I think the `c` type variable in `Fork` is breaking some assumption made about what GADTs look like. Should be easy to fix by weakening that check appropriately (@nikivazou will you be able to take a look?)

Not sure what you mean by measure with 2 fields - did you mean two parameters? 

If so, not really, because a measures are tied to _single_ datatypes (and their constructors).

But you can use `reflect` if you want to define functions over multiple parameters.

If you show a use case I can give some more help!

Best!

**Comment by bolt12** [comment] 2020-03-27 17:41
@ranjitjhala Thanks for your reply! I tweaked the GADT to make use of the quantified type variables but I still get the same error (might be useful to know):

```haskell
data Relation a b where
  Empty :: Relation Void Void
  One :: Int -> Relation () ()
  Join :: Relation c b -> Relation d b -> Relation (Either c d) b
  Fork :: Relation a c -> Relation a d -> Relation a (Either c d)

{-@
data Relation a b where
  Empty :: Relation Void Void
  | One :: {v:Int | v = 0 || v = 1} -> Relation () ()
  | Join :: Relation c b -> Relation d b -> Relation (Either c d) b
  | Fork :: Relation a c -> Relation a d -> Relation a (Either c d)
@-}
```

My idea is to define several relational calculus combinators on my matrix inductive structure and use those to specify properties using LH. For example I can have the following snippet (taken from [my laop library](https://hackage.haskell.org/package/laop-0.1.0.7/docs/LAoP-Matrix-Internal.html)):

```haskell
import Data.Void

data Relation a b where
  Empty :: Relation Void Void
  One :: Int -> Relation () ()
  Join :: Relation c b -> Relation d b -> Relation (Either c d) b
  Fork :: Relation a c -> Relation a d -> Relation a (Either c d)

-- Here I use a type 'Natural 0 1' but I wanted to try and refine the GADT.
{-@
data Relation a b where
  Empty :: Relation Void Void
  | One :: {v:Int | v = 0 || v = 1} -> Relation () ()
  | Join :: Relation c b -> Relation d b -> Relation (Either c d) b
  | Fork :: Relation a c -> Relation a d -> Relation a (Either c d)
@-}

-- (Eq, Num, Ord, etc.. instances ...)

comp :: Relation b c -> Relation a b -> Relation a c
comp Empty Empty           = Empty
comp (One a) (One b)       = One (a * b)
comp (Join a b) (Fork c d) = comp a c + comp b d         -- Divide-and-conquer law
comp (Fork a b) c          = Fork (comp a c) (comp b c) -- Fork fusion law
comp c (Join a b)          = Join (comp c a) (comp c b)  -- Join fusion law
```

Relational composition in combination with `(<=)` (which can be seen as relational inclusion) can be used to define a lot of other relational combinators (see [here](https://hackage.haskell.org/package/laop-0.1.0.7/docs/LAoP-Relation.html). This could be cool to have when using LH. I tried to add `reflect` to the signature of `comp` and I got the following error:

```
**** DONE:  A-Normalization ****************************************************


**** DONE:  Extracted Core using GHC *******************************************


**** DONE:  Transformed Core ***************************************************

liquid: safeBkArrow on RAllTforall c##X21b d##X21e .
(~#<[]> (TYPE 'GHC.Types.LiftedRep) (TYPE 'GHC.Types.LiftedRep) c##a2Nv (Data.Either.Either c##X21b d##X21e)) =>
lq_tmp$x##1728:(Relation.Relation c##X21b b##a2Nt) -> lq_tmp$x##1729:(Relation.Relation d##X21e b##a2Nt) -> (Relation.Relation c##a2Nv b##a2Nt)
CallStack (from HasCallStack):
error, called at src/Language/Haskell/Liquid/Types/Types.hs:1327:31 in liquidhaskell-0.8.6.0-8uYkE0Yspwt3GvEhvWjkte:Language.Haskell.Liquid.Types.Types
```

**Comment by nikivazou** [comment] 2020-03-31 12:54
> Hmm, thanks for filing this! I think the `c` type variable in `Fork` is breaking some assumption made about what GADTs look like. Should be easy to fix by weakening that check appropriately (@nikivazou will you be able to take a look?)
> 

@ranjitjhala  cannot promise when I will reach that, since I still do not have a good understanding of how GADTs work on LH.

**Comment by bolt12** [comment] 2020-03-31 14:46
Could you provide me with directions on how to learn about this? I can try
and have a look too! :)

**Comment by bolt12** [comment] 2020-04-06 14:47
@nikivazou  @ranjitjhala

**Comment by ranjitjhala** [comment] 2020-04-06 15:39
Hi Armando,

sorry for the late reply - too little time :(

The code for GADTs is a bit scattered, I *really* should have written a
paper
or description about it!

Anyways, I'll try to look it up today and get back to you later
this evening or tomorrow!

Thanks again so much!!!

- Ranjit

**Comment by bolt12** [comment] 2020-04-06 16:16
@ranjitjhala No problem, I understand :) I was worried you didn't get the notification because I forgot to tag you!

Take your time! Thanks!

**Comment by nikivazou** [comment] 2020-04-10 23:34
@bolt12 I added a partial fix for your solution in #1642. 
1. The "Bad Data Specification" error should be fixed, but 
2. the "safeBkArrow" is basically surpassed and will show up again if you start using reflection. 

Let me explain what is happening, in case you can help. 
When Liquid Haskell sees a case analysis, it is expanding all the cases to get precise checking (i.e., each alternative is checked in an environment specific for each data constructor). This case expansion happens here: https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Transforms/ANF.hs#L317
Now, in your example, the `Join` and `Fork` require "fancy" evidence in the case expansion (i.e., type coercions and application). There is a bug in LH's code when this expansion is happening (I did not investigate more). The crash on "safeBkArrow" that you get, can be read as "the type is not constructed well because it expect the proper type and coercion arguments". 

Here: https://github.com/ucsd-progsys/liquidhaskell/blob/69ff8d64833fe760296092ea896846f026a07c2d/tests/pos/T1633.hs I am basically suppressing this error: the `"--max-case-expand=0"` flag says "do not perform case expansion". Then, LH is loosing information and in this case it cannot prove that your `comp` function is exhaustively defined for all cases. So, I also added the flag `"--no-totality"` to disable totality checking.

**Comment by ranjitjhala** [comment] 2020-04-11 03:04
Wow, that's pretty interesting! thanks Niki!

Is there a way to tell when the ADT is "fancy", and then disable the
case-expansion automatically?

**Comment by nikivazou** [comment] 2020-04-11 07:26
No idea, I am still trying to understand GADTs :) 
But the proper fix I see is to still expand and provide the proper "fancy" evidence arguments on expansion.

**Comment by bolt12** [comment] 2020-04-11 10:52
What do you mean with "fancy" evidences? By looking at the code is difficult to understand what's going on, is there any reference document where I can start getting a feel how the internals work?

**Comment by nikivazou** [comment] 2020-04-11 12:28
Well, to address this problem one needs to know then internals of both Liquid Haskell and GHC. 
The "fancy" evidence refers to how case splitting is generated on GADTs by ghc. 
Concretely, Liquid Haskell analyses the intermediate representation of the haskell code you write, as it takes it from the GHC-API. 

To derive the intermediate code that is using GADTs, GHC is introducing these "fancy evidence" (i.e., type applications and coercions). Sadly, I do not know exactly how this exactly works and if there is a reference document for that.

**Comment by ranjitjhala** [comment] 2020-04-11 21:44
@bolt12 yes this probably requires familiarity with how GHC represents GADTs in its `Core Expr`.

Specifically (if I understand @nikivazou 's description) the issue is here: 

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Transforms/ANF.hs#L334-L346

In the above code we convert code like:

```haskell
head xs = case xs of 
                    (h:t) -> h 
                    DEFAULT -> patMatchError  
```

into code like

```haskell
head xs = case xs of 
                    (h:t) -> h 
                    [] -> patMatchError  
```

By *expanding* the `DEFAULT -> e` "arm" using all the constructors _not_ already matched
which is determined using

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/GHC/Misc.hs#L826-L837

For each "missing" data constructor, the above function returns a list `[(DataCon, [Type])]`
and then we generate the "cases" for each `DataCon` by creating variables of each `Type`

i.e. if we have a `(C, [t1, t2, t3])` in the list, we get a case

`C x1 x2 x3 -> e`

where `x1 :: t1`, `x2 :: t2` and `x3 :: t3`.

This is fine for "plain" data-types, but clearly there is some extra stuff going on with GADTs
that would be good to know. Specifically I wonder what

1. In your code, if you _manually_ put in all the missing cases, _what_ do those _patterns_ look like in the CORE?
2. If we can figure that out, then we can figure out how to generate those patterns automatically from the `DEFAULT`.

Does that make sense? @nikivazou am I on the right track or did I misunderstand?

**Comment by nikivazou** [comment] 2020-04-12 09:45
Exactly!

**Comment by bolt12** [comment] 2020-04-12 10:36
@ranjitjhala What do you mean with all the missing cases, the function is total! But I understand it might be too complicated for exploring. I can provide another simpler function with more straightforward pattern matching:

```haskell
-- | Matrix transposition.
tr :: Matrix e cols rows -> Matrix e rows cols
tr Empty      = Empty
tr (One e)    = One e
tr (Join a b) = Fork (tr a) (tr b)
tr (Fork a b) = Join (tr a) (tr b)
```

So for this code:

```haskell
data Relation a b where
  Empty :: Relation Void Void
  One :: Int -> Relation () ()
  Join :: Relation c b -> Relation d b -> Relation (Either c d) b
  Fork :: Relation a c -> Relation a d -> Relation a (Either c d)

tr :: Relation a b -> Relation b a
tr Empty      = Empty
tr (One e)    = One e
tr (Join a b) = Fork (tr a) (tr b)
tr (Fork a b) = Join (tr a) (tr b)
```

here's the core with `-ddump-simpl`

```haskell
==================== Tidy Core ====================
Result size of Tidy Core
  = {terms: 255, types: 276, coercions: 34, joins: 0/0}

-- RHS size: {terms: 1, types: 2, coercions: 2, joins: 0/0}
Alcuin.$WEmpty [InlPrag=INLINE[2]] :: Relation Void Void
[GblId[DataConWrapper],
 Caf=NoCafRefs,
 Str=m1,
 Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
         WorkFree=True, Expandable=True,
         Guidance=ALWAYS_IF(arity=0,unsat_ok=True,boring_ok=False)
         Tmpl= Alcuin.Empty
                 @ Void
                 @ Void
                 @~ (<Void>_N :: Void GHC.Prim.~# Void)
                 @~ (<Void>_N :: Void GHC.Prim.~# Void)}]
Alcuin.$WEmpty
  = Alcuin.Empty
      @ Void
      @ Void
      @~ (<Void>_N :: Void GHC.Prim.~# Void)
      @~ (<Void>_N :: Void GHC.Prim.~# Void)

-- RHS size: {terms: 3, types: 3, coercions: 2, joins: 0/0}
Alcuin.$WOne [InlPrag=INLINE[2]] :: Int -> Relation () ()
[GblId[DataConWrapper],
 Arity=1,
 Caf=NoCafRefs,
 Str=<L,U>m2,
 Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
         WorkFree=True, Expandable=True,
         Guidance=ALWAYS_IF(arity=1,unsat_ok=True,boring_ok=False)
         Tmpl= \ (dt_a1jo [Occ=Once] :: Int) ->
                 Alcuin.One
                   @ ()
                   @ ()
                   @~ (<()>_N :: () GHC.Prim.~# ())
                   @~ (<()>_N :: () GHC.Prim.~# ())
                   dt_a1jo}]
Alcuin.$WOne
  = \ (dt_a1jo [Occ=Once] :: Int) ->
      Alcuin.One
        @ ()
        @ ()
        @~ (<()>_N :: () GHC.Prim.~# ())
        @~ (<()>_N :: () GHC.Prim.~# ())
        dt_a1jo

-- RHS size: {terms: 8, types: 18, coercions: 3, joins: 0/0}
Alcuin.$WJoin [InlPrag=INLINE[2]]
  :: forall c b d.
     Relation c b -> Relation d b -> Relation (Either c d) b
[GblId[DataConWrapper],
 Arity=2,
 Caf=NoCafRefs,
 Str=<L,U><L,U>,
 Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
         WorkFree=True, Expandable=True,
         Guidance=ALWAYS_IF(arity=2,unsat_ok=True,boring_ok=False)
         Tmpl= \ (@ c_X112)
                 (@ b_a112)
                 (@ d_X115)
                 (dt_a1jy [Occ=Once] :: Relation c_X112 b_a112)
                 (dt_a1jz [Occ=Once] :: Relation d_X115 b_a112) ->
                 Alcuin.Join
                   @ (Either c_X112 d_X115)
                   @ b_a112
                   @ c_X112
                   @ d_X115
                   @~ (<Either c_X112 d_X115>_N
                       :: Either c_X112 d_X115 GHC.Prim.~# Either c_X112 d_X115)
                   dt_a1jy
                   dt_a1jz}]
Alcuin.$WJoin
  = \ (@ c_X112)
      (@ b_a112)
      (@ d_X115)
      (dt_a1jy [Occ=Once] :: Relation c_X112 b_a112)
      (dt_a1jz [Occ=Once] :: Relation d_X115 b_a112) ->
      Alcuin.Join
        @ (Either c_X112 d_X115)
        @ b_a112
        @ c_X112
        @ d_X115
        @~ (<Either c_X112 d_X115>_N
            :: Either c_X112 d_X115 GHC.Prim.~# Either c_X112 d_X115)
        dt_a1jy
        dt_a1jz

-- RHS size: {terms: 8, types: 18, coercions: 3, joins: 0/0}
Alcuin.$WFork [InlPrag=INLINE[2]]
  :: forall a c d.
     Relation a c -> Relation a d -> Relation a (Either c d)
[GblId[DataConWrapper],
 Arity=2,
 Caf=NoCafRefs,
 Str=<L,U><L,U>,
 Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
         WorkFree=True, Expandable=True,
         Guidance=ALWAYS_IF(arity=2,unsat_ok=True,boring_ok=False)
         Tmpl= \ (@ a_a13N)
                 (@ c_X13P)
                 (@ d_X13R)
                 (dt_a1jJ [Occ=Once] :: Relation a_a13N c_X13P)
                 (dt_a1jK [Occ=Once] :: Relation a_a13N d_X13R) ->
                 Alcuin.Fork
                   @ a_a13N
                   @ (Either c_X13P d_X13R)
                   @ c_X13P
                   @ d_X13R
                   @~ (<Either c_X13P d_X13R>_N
                       :: Either c_X13P d_X13R GHC.Prim.~# Either c_X13P d_X13R)
                   dt_a1jJ
                   dt_a1jK}]
Alcuin.$WFork
  = \ (@ a_a13N)
      (@ c_X13P)
      (@ d_X13R)
      (dt_a1jJ [Occ=Once] :: Relation a_a13N c_X13P)
      (dt_a1jK [Occ=Once] :: Relation a_a13N d_X13R) ->
      Alcuin.Fork
        @ a_a13N
        @ (Either c_X13P d_X13R)
        @ c_X13P
        @ d_X13R
        @~ (<Either c_X13P d_X13R>_N
            :: Either c_X13P d_X13R GHC.Prim.~# Either c_X13P d_X13R)
        dt_a1jJ
        dt_a1jK

Rec {
-- RHS size: {terms: 22, types: 97, coercions: 24, joins: 0/0}
tr [Occ=LoopBreaker] :: forall a b. Relation a b -> Relation b a
[GblId, Arity=1, Caf=NoCafRefs, Str=<S,1*U>, Unf=OtherCon []]
tr
  = \ (@ a_a1jY) (@ b_a1jZ) (ds_d1wB :: Relation a_a1jY b_a1jZ) ->
      case ds_d1wB of {
        Empty co_a1k1 co1_a1k2 ->
          Alcuin.$WEmpty
          `cast` ((Relation (Sym co1_a1k2) (Sym co_a1k1))_R
                  :: Relation Void Void ~R# Relation b_a1jZ a_a1jY);
        One co_a1k6 co1_a1k7 e_a13S ->
          (Alcuin.$WOne e_a13S)
          `cast` ((Relation (Sym co1_a1k7) (Sym co_a1k6))_R
                  :: Relation () () ~R# Relation b_a1jZ a_a1jY);
        Join @ c_a1kb @ d_a1kc co_a1kd a1_a13T b1_a13U ->
          (Alcuin.Fork
             @ b_a1jZ
             @ (Either c_a1kb d_a1kc)
             @ c_a1kb
             @ d_a1kc
             @~ (<Either c_a1kb d_a1kc>_N
                 :: Either c_a1kb d_a1kc GHC.Prim.~# Either c_a1kb d_a1kc)
             (tr @ c_a1kb @ b_a1jZ a1_a13T)
             (tr @ d_a1kc @ b_a1jZ b1_a13U))
          `cast` ((Relation <b_a1jZ>_N (Sym co_a1kd))_R
                  :: Relation b_a1jZ (Either c_a1kb d_a1kc)
                     ~R# Relation b_a1jZ a_a1jY);
        Fork @ c_a1kn @ d_a1ko co_a1kp a1_a13V b1_a13W ->
          (Alcuin.Join
             @ (Either c_a1kn d_a1ko)
             @ a_a1jY
             @ c_a1kn
             @ d_a1ko
             @~ (<Either c_a1kn d_a1ko>_N
                 :: Either c_a1kn d_a1ko GHC.Prim.~# Either c_a1kn d_a1ko)
             (tr @ a_a1jY @ c_a1kn a1_a13V)
             (tr @ a_a1jY @ d_a1ko b1_a13W))
          `cast` ((Relation (Sym co_a1kp) <a_a1jY>_N)_R
                  :: Relation (Either c_a1kn d_a1ko) a_a1jY
                     ~R# Relation b_a1jZ a_a1jY)
      }
end Rec }
```

Tell me if you need any more CORE information!

**Comment by nikivazou** [comment] 2020-04-17 17:07
The example works now with the `--no-totality` flag. That is, in general LH cannot check totality when case splitting on GADTs.

**Closed as completed by nikivazou** 2020-04-17 17:07 UTC

**Comment by bolt12** [comment] 2020-04-17 17:57
Thank you very much for your efforts! I'll try it!

**Comment by bolt12** [comment] 2020-04-17 18:12
I seem to encounter the following erro while trying to build the most recent version of `develop` branch

```haskell
/home/bolt/liquidhaskell/src/Language/Haskell/Liquid/Types/Types.hs:1144:14: error:
liquidhaskell                    >     • No instance for (Hashable F.Reft)
liquidhaskell                    >         arising from the 'deriving' clause of a data type declaration
liquidhaskell                    >       Possible fix:
liquidhaskell                    >         use a standalone 'deriving instance' declaration,
liquidhaskell                    >           so you can specify the instance context yourself
liquidhaskell                    >     • When deriving the instance for (Hashable DataDecl)
liquidhaskell                    >      |
liquidhaskell                    > 1144 |     deriving Hashable via Generically DataDecl
liquidhaskell                    >      |              ^^^^^^^^
liquidhaskell                    >
liquidhaskell                    > /home/bolt/liquidhaskell/src/Language/Haskell/Liquid/Types/Types.hs:1160:14: error:
liquidhaskell                    >     • No instance for (Hashable F.Reft)
liquidhaskell                    >         arising from the 'deriving' clause of a data type declaration
liquidhaskell                    >       Possible fix:
liquidhaskell                    >         use a standalone 'deriving instance' declaration,
liquidhaskell                    >           so you can specify the instance context yourself
liquidhaskell                    >     • When deriving the instance for (Hashable DataCtor)
liquidhaskell                    >      |
liquidhaskell                    > 1160 |     deriving Hashable via Generically DataCtor
```

**Comment by bolt12** [comment] 2020-04-17 20:16
@nikivazou

**Comment by nikivazou** [comment] 2020-04-18 06:50
`git module update` to get the linked fixpoint?

**Comment by bolt12** [comment] 2020-04-18 09:32
@nikivazou  yes, seems like I forgot to do that! Thanks!

**Comment by bolt12** [comment] 2020-04-18 10:39
@nikivazou  @ranjitjhala 

The example works fine now but I'm having trouble with this simple example:

```haskell
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE GADTs #-}

module Alcuin where

import Data.Void

data Relation a b where
  Empty :: Relation Void Void
  One :: Bool -> Relation () ()
  Join :: Relation c b -> Relation d b -> Relation (Either c d) b
  Fork :: Relation a c -> Relation a d -> Relation a (Either c d)

deriving instance Show (Relation a b)

instance Eq (Relation a b) where
  Empty == Empty               = True
  (One a) == (One b)           = a == b
  (Join a b) == (Join c d)     = a == c && b == d
  (Fork a b) == (Fork c d)     = a == c && b == d
  x@(Fork _ _) == y@(Join _ _) = x == abideJF y
  x@(Join _ _) == y@(Fork _ _) = abideJF x == y

addR :: Relation a b -> Relation a b -> Relation a b
addR Empty Empty               = Empty
addR (One a) (One b)           = One (a || b)
addR (Join a b) (Join c d)     = Join (addR a c) (addR b d)
addR (Fork a b) (Fork c d)     = Fork (addR a c) (addR b d)
addR x@(Fork _ _) y@(Join _ _) = addR x (abideJF y)
addR x@(Join _ _) y@(Fork _ _) = addR (abideJF x) y

subR :: Relation a b -> Relation a b -> Relation a b
subR Empty Empty               = Empty
subR (One True) (One True)     = One False
subR (One True) (One False)    = One True
subR (One False) (One True)    = One False
subR (One False) (One False)   = One False
subR (Join a b) (Join c d)     = Join (subR a c) (subR b d)
subR (Fork a b) (Fork c d)     = Fork (subR a c) (subR b d)
subR x@(Fork _ _) y@(Join _ _) = subR x (abideJF y)
subR x@(Join _ _) y@(Fork _ _) = subR (abideJF x) y

mulR :: Relation a b -> Relation a b -> Relation a b
mulR Empty Empty               = Empty
mulR (One a) (One b)           = One (a && b)
mulR (Join a b) (Join c d)     = Join (mulR a c) (mulR b d)
mulR (Fork a b) (Fork c d)     = Fork (mulR a c) (mulR b d)
mulR x@(Fork _ _) y@(Join _ _) = mulR x (abideJF y)
mulR x@(Join _ _) y@(Fork _ _) = mulR (abideJF x) y

instance Ord (Relation a b) where
    Empty <= Empty               = True
    (One a) <= (One b)           = a <= b
    (Join a b) <= (Join c d)     = (a <= c) && (b <= d)
    (Fork a b) <= (Fork c d)     = (a <= c) && (b <= d)
    x@(Fork _ _) <= y@(Join _ _) = x <= abideJF y
    x@(Join _ _) <= y@(Fork _ _) = abideJF x <= y

{-@ reflect abideJF @-}
abideJF :: Relation a b -> Relation a b
abideJF (Join (Fork a c) (Fork b d)) = Fork (Join (abideJF a) (abideJF b)) (Join (abideJF c) (abideJF d)) -- Join-Fork abide law
abideJF Empty                        = Empty
abideJF (One e)                      = One e
abideJF (Join a b)                   = Join (abideJF a) (abideJF b)
abideJF (Fork a b)                   = Fork (abideJF a) (abideJF b)

{-@ reflect comp @-}
comp :: Relation b c -> Relation a b -> Relation a c
comp Empty Empty           = Empty
comp (One a) (One b)       = One (a && b)
comp (Join a b) (Fork c d) = comp a c `addR` comp b d -- Divide-and-conquer law
comp (Fork a b) c          = Fork (comp a c) (comp b c) -- Fork fusion law
comp c (Join a b)          = Join (comp c a) (comp c b) -- Join fusion law

{-@ reflect tr @-}
tr :: Relation a b -> Relation b a
tr Empty      = Empty
tr (One e)    = One e
tr (Join a b) = Fork (tr a) (tr b)
tr (Fork a b) = Join (tr a) (tr b)
```

This is giving me this errors:

```haskell
**** RESULT: UNSAFE ************************************************************


/home/bolt/Desktop/Bolt/Playground/Haskell/test/src/Alcuin.hs:(25,1)-(30,51): Error: Liquid Type Mismatch

25 | addR Empty Empty               = Empty
26 | addR (One a) (One b)           = One (a || b)
27 | addR (Join a b) (Join c d)     = Join (addR a c) (addR b d)
28 | addR (Fork a b) (Fork c d)     = Fork (addR a c) (addR b d)
29 | addR x@(Fork _ _) y@(Join _ _) = addR x (abideJF y)
30 | addR x@(Join _ _) y@(Fork _ _) = addR (abideJF x) y

Inferred type
VV : {v : GHC.Prim.Addr# | v == "/home/bolt/Desktop/Bolt/Playground/Haskell/test/src/Alcuin.hs:(25,1)-(30,51)|functionaddR"}

not a subtype of Required type
VV : {VV : GHC.Prim.Addr# | 5 < 4}



/home/bolt/Desktop/Bolt/Playground/Haskell/test/src/Alcuin.hs:(33,1)-(41,51): Error: Liquid Type Mismatch

33 | subR Empty Empty               = Empty
34 | subR (One True) (One True)     = One False
35 | subR (One True) (One False)    = One True
36 | subR (One False) (One True)    = One False
37 | subR (One False) (One False)   = One False
38 | subR (Join a b) (Join c d)     = Join (subR a c) (subR b d)
39 | subR (Fork a b) (Fork c d)     = Fork (subR a c) (subR b d)
40 | subR x@(Fork _ _) y@(Join _ _) = subR x (abideJF y)
41 | subR x@(Join _ _) y@(Fork _ _) = subR (abideJF x) y

Inferred type
VV : {v : GHC.Prim.Addr# | v == "/home/bolt/Desktop/Bolt/Playground/Haskell/test/src/Alcuin.hs:(33,1)-(41,51)|functionsubR"}

not a subtype of Required type
VV : {VV : GHC.Prim.Addr# | 5 < 4}



/home/bolt/Desktop/Bolt/Playground/Haskell/test/src/Alcuin.hs:(44,1)-(49,51): Error: Liquid Type Mismatch

44 | mulR Empty Empty               = Empty
45 | mulR (One a) (One b)           = One (a && b)
46 | mulR (Join a b) (Join c d)     = Join (mulR a c) (mulR b d)
47 | mulR (Fork a b) (Fork c d)     = Fork (mulR a c) (mulR b d)
48 | mulR x@(Fork _ _) y@(Join _ _) = mulR x (abideJF y)
49 | mulR x@(Join _ _) y@(Fork _ _) = mulR (abideJF x) y

Inferred type
VV : {v : GHC.Prim.Addr# | v == "/home/bolt/Desktop/Bolt/Playground/Haskell/test/src/Alcuin.hs:(44,1)-(49,51)|functionmulR"}

not a subtype of Required type
VV : {VV : GHC.Prim.Addr# | 5 < 4}



/home/bolt/Desktop/Bolt/Playground/Haskell/test/src/Alcuin.hs:(69,1)-(73,55): Error: Liquid Type Mismatch

69 | comp Empty Empty           = Empty
70 | comp (One a) (One b)       = One (a && b)
71 | comp (Join a b) (Fork c d) = comp a c `addR` comp b d -- Divide-and-conquer law
72 | comp (Fork a b) c          = Fork (comp a c) (comp b c) -- Fork fusion law
73 | comp c (Join a b)          = Join (comp c a) (comp c b) -- Join fusion law

Inferred type
VV : {v : GHC.Prim.Addr# | v == "/home/bolt/Desktop/Bolt/Playground/Haskell/test/src/Alcuin.hs:(69,1)-(73,55)|functioncomp"}

not a subtype of Required type
VV : {VV : GHC.Prim.Addr# | 5 < 4}
```

I'm running liquid haskell with --no-termination flag since by some reason it cannot detect the termination of `addR`/`subR`/`mulR`. Any help figuring out this problem? What does this:

```haskell
not a subtype of Required type
VV : {VV : GHC.Prim.Addr# | 5 < 4}
```

means?

**Comment by nikivazou** [comment] 2020-04-18 11:03
It is the totality checker. Do you run it without the totality checker? i.e., using the flag `no-totality`

**Comment by bolt12** [comment] 2020-04-18 11:06
Yes I was missing that! Everything works fine now! Sorry for your trouble!
