### ISSUE TITLE
Polymorphic instantiation seems broken with typeclasses

### ISSUE THREAD

**Issue by rosekunkel** [ucsd-progsys/liquidhaskell#1619] opened 2020-02-22 08:24 UTC
Liquid deems `fmapPreservesLabel` unsafe, but its equivalent using explicit dictionary passing, `myFmapPreservesLabel`, is deemed safe. They should both be safe, since `fmap`/`myFmap` should be instantiated at `Tagged Label<label>`.
```haskell
{-# LANGUAGE Rank2Types #-}

{-@ data Label<label :: User -> Bool> where @-}
data Label
data User
data Tagged l a = Tag a
data MyFunctor f = MyFunctor { myFmap :: forall a b. (a -> b) -> f a -> f b }

instance Functor (Tagged l) where
  fmap = fmapTagged

taggedFunctor :: MyFunctor (Tagged l)
taggedFunctor = MyFunctor fmapTagged

fmapTagged :: (a -> b) -> Tagged l a -> Tagged l b
fmapTagged f (Tag x) = Tag (f x)

{-@
myFmapPreservesLabel :: forall <label :: User -> Bool>.
(a -> b) -> Tagged (Label<label>) a -> Tagged (Label<label>) b
@-}
myFmapPreservesLabel :: (a -> b) -> Tagged Label a -> Tagged Label b
myFmapPreservesLabel = myFmap taggedFunctor

{-@
fmapPreservesLabel :: forall <label :: User -> Bool>.
(a -> b) -> Tagged (Label<label>) a -> Tagged (Label<label>) b
@-}
fmapPreservesLabel :: (a -> b) -> Tagged Label a -> Tagged Label b
fmapPreservesLabel = fmap
```

**Comment by ranjitjhala** [comment] 2020-02-22 15:59
I don’t think it’s the type class, more likely the HKT — LH is (probably)
not doing any polymorphic instantiation when argument used in the type
application is NOT of kind * Ie it ONLY does instantiation when the type IS
of kind * (that’s my guess.)


GHC desugars the fmap into

fmap @ Tagged Label @ a @ b

And my guess is LH is not doing any instantiation for the Tagged Label.

I wonder why the other version passes... maybe because LH instantiates the
l in the sig for the dictionary?

**Comment by rosekunkel** [comment] 2020-02-23 23:37
I should mention that this is currently blocking my attempt to rewrite Binah in the MAC style. (Well, not blocking exactly, but it means none of the code can use do-notation or monad transformers, which is very unfortunate).

**Comment by ranjitjhala** [comment] 2020-02-23 23:48
@niki vazou <nikivazou@gmail.com> any chance you can look at this soon?

I think it's either really easy or really hard to add this feature :-)

(btw, why should do notation come into play here? Looks like the problem is
with fmap?
or is it that the issue is just a simplification and the problem also
arises with
the type of >>= etc.?)

**Comment by rosekunkel** [comment] 2020-02-23 23:50
It also happens with `>>=` (and I think basically every HKT typeclass).

**Comment by jprider63** [comment] 2020-02-24 03:25
I'm not sure if this is helpful, but Yiyun, Niki, and I are close to getting typeclasses working. `Functor` seems to mostly work, but there are a few issues we're still resolving. We can share the branch when it's fully working.

**Comment by nikivazou** [comment] 2020-02-24 07:37
@rosekunkel, it looks indeed like an instantiation problem. The below is SAFE. Would that unblock  you, or should I look deeper? 
```
{-# LANGUAGE Rank2Types #-}
{-# LANGUAGE FlexibleInstances #-}

{-@ data Label<label :: User -> Bool> where @-}
data Label
data User
data Tagged l a = Tag a
data MyFunctor f = MyFunctor { myFmap :: forall a b. (a -> b) -> f a -> f b }

instance Functor (Tagged Label) where
{-@ instance Functor (Tagged Label) where 
    fmap :: forall <label :: User -> Bool>. (a -> b) -> Tagged (Label<label>) a -> Tagged (Label<label>) b
    @-}
  fmap = fmapTagged

fmapTagged :: (a -> b) -> Tagged l a -> Tagged l b
fmapTagged f (Tag x) = Tag (f x)


{-@
fmapPreservesLabel :: forall <label :: User -> Bool>.
(a -> b) -> Tagged (Label<label>) a -> Tagged (Label<label>) b
@-}
fmapPreservesLabel :: (a -> b) -> Tagged Label a -> Tagged Label b
fmapPreservesLabel = fmap
```

**Comment by rosekunkel** [comment] 2020-02-24 08:30
That technically unblocks me, but it removes a lot of the advantage of
using the MAC encoding over the current one - since the type of `>>=` will
have to be similarly refined, we can't treat `Tagged Label` as a normal
monad. So all the monad combinators won't preserve the label automatically,
which they would by polymorphism for `Tagged l`.

**Comment by nikivazou** [comment] 2020-02-24 08:41
I am not following your reasoning 100%. 
The one encoding is polymorphic over the type `l` and the other over the abstract refinement `l`. 
So, the encodings seem equivalent. 

At any case, I will try to take a deeper look into this later today.

**Comment by rosekunkel** [comment] 2020-02-24 08:59
For example, if we tried to use `sequence` on a list of tagged values,
sequence would get the type
`[Tagged Label a] -> Tagged Label [a]`, not `forall <label :: User ->
Bool>. [Tagged Label<label> a] -> Tagged Label<label> [a]`. If instead the
monad instance is for `Tagged l`, then sequence would get the type `[Tagged
l a] -> Tagged l [a]`, and then `l` could be instantiated with
`Label<label>`. In essence your solution tells LH that >>= has a special
type for Tagged Label, but what I think we really want is to be able to
tell LH that the monad instance for Tagged is really `instance forall
<label :: User -> Bool>. Monad (Tagged Label<label>)`. That syntax doesn't
exist, though.

**Comment by nikivazou** [comment] 2020-02-24 09:05
Hmmm interesting. 

Ok, I think I got the problem (or a problem...), are you on slack?

**Comment by nikivazou** [comment] 2020-02-25 17:32
So, #1621 has a fix for that where the Functor is added in the generic type classes. 
The problem might also be solved by adding abstract refinements, which is currently not supported bu LH.

**Closed as completed by nikivazou** 2020-02-25 17:32 UTC

**Comment by ranjitjhala** [comment] 2020-02-25 18:26
Btw modifying the isGeneric should also address the “sequence” issue right?

**Comment by nikivazou** [comment] 2020-02-26 19:40
I suspect so, but you would need to say that `Monad` is generic type class. 
From that, it would not suffice to add abstract refinements only to `fmap`, but to many more methods.

**Comment by ranjitjhala** [comment] 2020-02-26 19:45
Yes, I was including Monad etc. too...
