### ISSUE TITLE
Extend Structural Termination 

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1381] opened 2018-12-02 05:16 UTC
The new structural checker by @nomeata is awesome. Would be great to extend it to handle things like:

```haskell
data Pea = Z | S Pea

foo :: Int -> Pea -> Int 
foo n Z     = n
foo n (S p) = foo (n + 1) p  
```

**Comment by nomeata** [comment] 2018-12-02 09:25
It doesn't? Why not? Seems like a bug to me.

Oh, you mean because it needs to guess the order of arguments more cleverly?

**Comment by ranjitjhala** [comment] 2018-12-02 15:22
Yes, I thought it was doing something about guessing the arguments but
apparently not.

**Comment by nomeata** [comment] 2018-12-02 16:16
No, it still assumes lexicographic order. Maybe it skips arguments that are not algebraic, don't remember.

**Comment by nomeata** [comment] 2018-12-02 21:16
No, it does not, but it skips non-algebraic arguments that stay the same (important for `map f (x:xs) = f x : map f xs`), see this code: https://github.com/ucsd-progsys/liquidhaskell/blob/3f21e54310f1e385a2111fc04922e88fa5ff2371/src/Language/Haskell/Liquid/Termination/Structural.hs#L161

In Isabelle, it collects for each function call which arguments are decreasing, strictly decreasing, or possibly increasing, and afterwards tries to guess the right order of arguments. So it is all doable… 
Alternatively, the user could specify which argument is structurally recursive (but then they can just state a measure…)
Anyways, one has to stop somewhere.

**Comment by nomeata** [comment] 2018-12-02 21:17
Also, not sure this is “easy” ;-)

**Comment by ranjitjhala** [comment] 2018-12-02 21:37
Ah both of those - the Isabelle approach and specifying the args - sound
great.

Maybe will look into the latter first!

**Comment by rosekunkel** [comment] 2019-01-19 01:29
I have a working implementation of an order-independent termination checker, but it still can't check the example in this issue. I think LH is assuming the first Int argument is the decreasing parameter before it attempts to run the structural termination checker. @ranjitjhala do you know where I should look to change that?

**Comment by ranjitjhala** [comment] 2019-01-19 02:01
Hmm pretty sure the structural checker is run first and
only things it fails on are handed off to the metric checker.

See this:

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Liquid.hs#L184

the `generateConstraints` (which is where the metric based checking
happens,
together with other refinement-typing constraints) is only called on
`info3`
where we have (laboriously) added the results of `ST.terminationVars i`.

Are you sure the termination checker is doing its business correctly?

You may want to change this line

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/Termination/Structural.hs#L19

terminationVars = tracepp "terminationVars" . resultVars . terminationCheck
to check that in fact the right thing is happening?

**Comment by rosekunkel** [comment] 2019-01-19 02:17
Well I went to double check and I can no longer reproduce the problem. I'm not sure what I changed...

**Comment by ranjitjhala** [comment] 2019-01-23 04:48
@rosekunkel (due to @morteako) I came across this odd error, is it related to / fixed by the above?

```haskell
{-@ LIQUID "--reflection"     @-}
{-@ LIQUID "--no-adt"         @-}
{-@ LIQUID "--ple"            @-}

module FingerTree where 

import Language.Haskell.Liquid.ProofCombinators 

{-@ measure digitSize @-}
digitSize :: Digit a -> Int
digitSize (One {}) = 1
digitSize (Two {}) = 2
digitSize (Three {}) = 3
digitSize (Four {}) = 4

data Digit a
    = One a
    | Two a a
    | Three a a a
    | Four a a a a
    deriving (Show)

data Node a = Node2 {a2::a, b2::a} | Node3 {a3::a, b3::a, c3:: a}
    deriving (Show)

data FingerTree a
    = Empty
    | Single a
    | Deep (Digit a) (FingerTree (Node a)) (Digit a)
    deriving Show

{-@ reflect fingerTreeSize @-}
fingerTreeSize :: FingerTree a -> Int
fingerTreeSize t = size to1 t 

{-@ reflect size @-}
size :: (a -> Int) -> FingerTree a -> Int
size _ Empty        = 0
size f (Single a)   = f a
size f (Deep l m r) = digitS f l + size (nodeS f) m + digitS f r

{-@ reflect digitS @-} 
digitS :: (a -> Int) -> Digit a -> Int
digitS f (One a)        = f a
digitS f (Two a b)      = f a + f b
digitS f (Three a b c)  = f a + f b + f c
digitS f (Four a b c d) = f a + f b + f c + f d

{-@ reflect nodeS @-}
nodeS :: (a -> Int) -> Node a -> Int
nodeS f (Node2 a b)   = f a + f b
nodeS f (Node3 a b c) = f a + f b + f c

{-@ reflect consts @-}
consts a b = a

{-@ reflect to1 @-}
to1 :: a -> Int
to1 _ = 1

{-@ n2Int1 :: a:Int -> b:Int -> {n:Node Int | nodeS to1 n == 2} @-}
n2Int1 :: Int -> Int -> Node Int
n2Int1 a b = Node2 a b

{-@ measure isEmpty @-}
isEmpty Empty      = True
isEmpty (Single _) = False
isEmpty Deep{}     = False

{-@ singleton :: v:Int -> {ft:FingerTree Int | isEmpty ft} @-}
singleton :: Int -> FingerTree Int
singleton a = Empty 

{-@ fromList :: xs:_ -> {t:_ | fingerTreeSize t == len xs} @-}
fromList :: [a] -> FingerTree a
fromList []     = Empty
fromList (x:xs) = add x (fromList xs)

{-@ infix <| @-}
-- | /O(1)/. Add an element to the left end of a sequence.
-- Mnemonic: a triangle with the single element at the pointy end.
{- (<|) :: a -> ft:FingerTree a -> {v : FingerTree a | fingerTreeSize v == fingerTreeSize ft + 1} @-}
{-@ reflect <| @-}
(<|) :: a -> FingerTree a -> FingerTree a
a <| Empty                    =  Single a
a <| Single b                 =  Deep (One a) Empty (One b)
a <| Deep (Four b c d e) m sf = {- m `seq` -} Deep (Two a b) (Node3 c d e <| m) sf
a <| Deep l m r               = Deep (consDigit a l) m r 

{-@ lem_add :: f:_ -> a:_ -> t:_ -> { size f (a <| t) == size f t + f a }  @-}
lem_add :: (a -> Int) -> a -> FingerTree a -> () 

lem_add f _ Empty       
  = () 

lem_add f _ (Single {}) 
  = () 

lem_add f a t@(Deep (Four b c d e) m sf) 
  =   size f t + f a 
  === digitS f (Four b c d e) + size (nodeS f) m + digitS f sf + f a
  === f a + f b + digitS f sf + f c + f d + f e + size (nodeS f) m 
  === f a + f b + digitS f sf + nodeS f (Node3 c d e) + size (nodeS f) m 
      ? lem_add (nodeS f) (Node3 c d e) m
  === f a + f b + digitS f sf + size (nodeS f) ((Node3 c d e) <| m)
  === size f (Deep (Two a b) ((Node3 c d e) <| m) sf)
  === size f (a <| (Deep (Four b c d e) m sf)) 
  === size f (a <| t)
  *** QED  

lem_add f a t@(Deep l m r)  
  = () 
```

It seems like the structural checker does not check `lem_add`, and then LH complains with:

```
No decreasing parameter
```

but if you flip the arguments to `lem_add` and put the `FingerTree` first then its ok.

This seems odd? Any clue?

**Comment by rosekunkel** [comment] 2019-01-23 05:54
The code seems to be missing some definitions, so I can't say for sure, but I would expect this to be fixed by this change. In particular, the termination checker currently assumes that unchanging arguments come first, followed by decreasing arguments. Since e.g. `(nodeS f)` is neither, it gives up before reaching the `FingerTree` parameter.

**Comment by ranjitjhala** [comment] 2019-01-24 14:24
Great! Was there a PR already that we can merge?

**Comment by rosekunkel** [comment] 2019-01-24 18:21
Not yet; I'll get one up today. I wanted to make a few more tests.

**Comment by ranjitjhala** [comment] 2019-01-24 18:30
awesome thanks!!

**Closed as completed** 2019-01-25 17:48 UTC
Labels: enhancement, easy, termination, proposal
