### ISSUE TITLE
Strange errors with Prelude and Stack

### ISSUE THREAD

**Issue by varosi** [ucsd-progsys/liquidhaskell#1210] opened 2017-12-26 22:50 UTC
I'm trying this:

> D:\Projects>stack exec -- liquid test.hs
> LiquidHaskell v0.8.2.0 Copyright 2013-17 Regents of the University of California. All Rights Reserved.
> 
> liquid.EXE: Main: Could not find module `Prelude'
> There are files missing in the `base-4.10.1.0' package,
> try running 'ghc-pkg check'.
> Use -v to see a list of the files searched for.

on Windows 10 with LiquidHaskell built from source from GitHub (GHC-8.2.1 using Stack). While running it with lts-10.0 in global-project/stack.yaml.
If I switch to nightly-2017-11-24 resolver in global-project/stack.yaml then LiquidHaskell changes error to:

> D:\Projects>stack exec -- liquid test.hs
> LiquidHaskell v0.8.2.0 Copyright 2013-17 Regents of the University of California. All Rights Reserved.
> 
> realgcc.exe: fatal error: no input files
> compilation terminated.
> liquid.EXE: `gcc.exe' failed in phase `gcc'. (Exit code: 1)

**Comment by ranjitjhala** [comment] 2017-12-27 00:18
Unfortunately we've seen this same "realgcc" issue before (on windows) and
really don't know what the problem is; it is some odd interaction of stack
& ghc 8.2.

One person was able to fix this by installing LH using the new WSL/bash
feature available on 64-bit windows 10

**Comment by varosi** [comment] 2017-12-27 15:39
Is it possible to debug it somehow? I tried with "-v" option, but it does not show more information.

**Comment by varosi** [comment] 2018-01-02 21:13
Are there a pre-built Windows binaries somewhere?

**Comment by MatthijsBlom** [comment] 2018-08-16 23:15
I, too, am curious what could possibly be done to debug this.

@ranjitjhala I have built liquid several times, using both cabal-install and stack, with the exact same result each time. Therefore I do not think this is the result of an interaction with stack.

When I use stack to invoke liquid, the error message changes;

```
C:\...> liquid Main.hs
LiquidHaskell Version 0.8.2.4, Git revision b78152f170bb19f0ddb6e72bfa1e5b3343e5de3c (dirty)
Copyright 2013-18 Regents of the University of California. All Rights Reserved.

realgcc.exe: fatal error: no input files
compilation terminated.
liquid: `gcc.exe' failed in phase `gcc'. (Exit code: 1)
```

```
C:\...> stack exec -- liquid Main.hs
LiquidHaskell Version 0.8.2.4, Git revision b78152f170bb19f0ddb6e72bfa1e5b3343e5de3c (dirty)
Copyright 2013-18 Regents of the University of California. All Rights Reserved.

liquid.EXE: C:\Users\Matthijs\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\lib\package.conf.d\package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not enough bytes)
```

**Comment by ranjitjhala** [comment] 2018-08-17 01:53
Very puzzling ... do you know if others have seen this “realgcc” problem
before? Maybe using GHC on windows?

Let me do some googling...

**Comment by facundominguez** [comment] 2024-06-14 18:30
Closing since the `liquid` executable has been removed.

**Closed as completed by facundominguez** 2024-06-14 18:30 UTC
