### ISSUE TITLE
Odd behavior with tuples

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1390] opened 2018-12-21 17:03 UTC
LH refuses to check `fails` even though various simple variants work fine. (Most mysterious is when we change the definition of `State`.) My hunch is it has to do with some combination of:

- Abstract refinements
- Core translation
- Gremlins

```haskell
{-@ LIQUID "--reflection"  @-}

module TupleBug where 

-- 1. If you replace `State` with `data State = St` or some such, it works fine! 
-- 2. If you replace `Jim` so it takes a SINGLE `State` parameter, it works fine! 

type State = () 
type Com   = Int 

data And a b = And a b 

--------------------------------------------------------------------------------

{-@ type Jim C = sIn:State -> sOut:State -> {v:() | bstep C sIn sOut} @-}
type JimT = State -> State -> () 

{-@ reflect bstep @-}
bstep :: Com -> State -> State -> Bool 
bstep _ _ _ = True 

-- Why does this fail?
{-@ fail :: c:_ -> (a, Jim c) -> (Jim c) @-} 
fail :: Com -> (a, JimT) -> JimT 
fail c (_, p) = p 

-- This is fine ...
{-@ ok1 :: c:_ -> (Jim c, _) -> Jim c @-} 
ok1 :: Com -> (JimT, a) -> JimT 
ok1 c (p, _) = p 

-- And this is also fine ... 
{-@ ok2 :: c:_ -> And () (Jim c) -> (Jim c) @-} 
ok2 :: Com -> And () JimT -> JimT 
ok2 c (And _ p) = p 
```

**Comment by ranjitjhala** [comment] 2018-12-21 17:04
@nikivazou have you ever run across the above issue? Its most puzzling.

**Comment by facundominguez** [comment] 2024-06-02 18:27
Closing since I can't reproduce it in the latest LH.

**Closed as completed by facundominguez** 2024-06-02 18:27 UTC
