### ISSUE TITLE
well formedness confusion on imported modules

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1393] opened 2019-01-11 11:17 UTC
Consider the following three modules: 

```haskell
module C where 

{-@ reflect cProp @-}

cProp :: Eq a => a -> a -> Bool 
cProp x y = x == y 
```

```haskell
module B where 

import C

data B a = B {b1 :: a, b2 :: a }
{-@ data B a = B {b1 :: a, b2 :: {v:a | cProp b1 v } } @-}
```

```haskell
module A where 

import B 

a :: Eq a => B a -> Bool 
a (B x y) = x == y 
```

`liquid` is SAFE on modules `B` and `C`, but running liquid on module `A` returns 

```
 B.hs:6:10-11: Error: Illegal type specification for `B.b2`

 6 | {-@ data B a = B {b1 :: a, b2 :: {v:a | cProp b1 v } } @-}
```

This is very confusing, since module `B` is safe (but `cProp` is out of scope in module `A`).
I do not think checking module `A` should check the specifications of `B` on `A`'s module environment.

**Comment by ranjitjhala** [comment] 2019-01-11 16:04
This, unfortunately is a  hard problem, that I’ve seen before. The problem is this: how do you hide parts of a refinement of a constructor for example because those parts are no longer in scope? Right now the simplest workaround is just to transitively import all the modules. This is a bit silly I agree but honestly I don’t know what a good solution is.

**Comment by nikivazou** [comment] 2019-01-11 17:26
There are other potential "silly" solutions, like 
- prune from A all predicates not in scope or 
- make B reexport all the refinements that appear on the data constructors. 

I too do not know which one is better. But if we keep it as is, we should change the error message, when checking the imported modules.

**Comment by ranjitjhala** [comment] 2019-01-25 18:03
[For the record] I like @nikivazou 's suggestion that the saved `.bspec` files should be "closed", i.e. should pull in transitive dependencies. I do worry whether the GHC names are in scope though, but that's another issue...

**Comment by facundominguez** [comment] 2024-06-02 17:39
Closing this since I can't reproduce it in the latest LH.

**Closed as completed by facundominguez** 2024-06-02 17:39 UTC
Labels: question, modules, researchy
