### ISSUE TITLE
Current version of LH seems to forget some refinements of type constructors

### ISSUE THREAD

**Issue by michaelborkowski** [ucsd-progsys/liquidhaskell#1777] opened 2020-10-08 18:48 UTC
I'm on the latest version of LH (commit 2a68368ac86743ec5d7dda57416a78076e88223b from the develop branch) and noticed some simple lemmas failing to check. I believe LH may be ignoring some information from refinements of GADTs when the information about the type is imported into another file. 

For example, consider the following two modules

https://github.com/michaelborkowski/liquidmeta_public/blob/master/BasicsTest1.hs which contains
```
data FEnv = FEmpty                       -- type FEnv = [(Vname, FType) or Vname]
          | FCons  Vname FType FEnv
          | FConsT Vname Kind  FEnv
  deriving (Show) 
{-@ data FEnv where
    FEmpty :: FEnv
    FCons  :: x:Vname -> t:FType -> { g:FEnv | not (in_envF x g) } -> FEnv
    FConsT :: a:Vname -> k:Kind  -> { g:FEnv | not (in_envF a g) } -> FEnv @-}
```

FEnv is just a variable binding environment and the refinement on the FCons and FConsT constructors says that the sequence of variables must be unique. Now consider the lemma/function `simple` which appears in this file and also in a separate file https://github.com/michaelborkowski/liquidmeta_public/blob/master/BasicsTest2.hs under the name `simple'`:

```
{-@ simple :: g:FEnv -> { a:Vname | in_envF a g } -> { k:Kind | tv_bound_inF a k g }
                -> { g':FEnv | not (in_envF a g') } @-}
simple :: FEnv -> Vname -> Kind -> FEnv
simple g a k  = case g of
  (FCons y s g')    -> case ( a == y ) of   
        (False)     -> simple g' a k
  (FConsT a' k' g') -> case ( a == a' ) of
        (True)      -> g'      
        (False)     -> simple g' a k
```

Given environment `g` and `a \in g` we must produce an environment not containing `a`. Despite being identical, `simple` typechecks as safe, but `simple'` in BasicsTest2.hs does not.

In the .html file produced by LH, if you mouse-over g' in line 67 in  https://github.com/michaelborkowski/liquidmeta_public/blob/master/BasicsTest1.hs.html
we learn that g' is inferred to have type
`{v : BasicsTest1.FEnv | not (in_envF y v) && v == g'}`

But if you mouse-over line 20 in https://github.com/michaelborkowski/liquidmeta_public/blob/master/BasicsTest2.hs.html
we see that g' is only inferred to have the weaker type
`{v : BasicsTest1.FEnv | v == g'}`

This problem is not present on the previous version of LH that I was using (both files check as safe):

LiquidHaskell Version 0.8.10.1, Git revision 355eb97093db50f864644b99e7da8995d27e7b61 (dirty) [develop@355eb97093db50f864644b99e7da8995d27e7b61 (Fri Jul 24 08:06:15 2020 +0200)]

**Comment by ranjitjhala** [comment] 2020-10-09 22:47
@adinapoli this looks like a regression.

There is a module `Lib` and `Client` with `simple` defined in `Lib` and a copy `simple'` in `Client`.

* Both `simple` and `simple'` verify in `355eb97093db50f864644b99e7da8995d27e7b61` 

* Only `simple` (in `Lib`) **but not** `simple'` (in `Client`) verify in the current `2a68368ac86743ec5d7dda57416a78076e88223b`

I'll keep digging and let you know.

**Comment by ranjitjhala** [comment] 2020-10-09 23:42
Here's a super stripped down version.

1. Define a refined datatype in `Lib`
2. Import it in `Client`
3. The refinements on the datatype seem to get *erased* in `Client`!

**Note** the `reflection` flag is important; without it, `Client` fails (as it should!)

@nikivazou  will you have cycles to take a look at this?

**Library**

```haskell
{-@ LIQUID "--reflection"  @-}       -- this is important!

module Lib where

data FEnv = FCons Int

{-@ data FEnv where
    FCons  :: { g:Int | False } -> FEnv
    @-}

{-@ foo :: a:{_ | False } -> _ @-}           -- <<< We need the precondition `False` to check `foo`
foo a = FCons a
```

**Client**

```haskell
module Client where

import Lib

{-@ foo :: a:{_ | True} -> _ @-}    --- <<<< we DO NOT need the precondition `False`; refinements on `FCons` get erased?
foo a = FCons a
```

**Comment by nikivazou** [comment] 2020-10-10 08:57
Seems like a Parsing issue. @kosmikus can you check this again https://github.com/ucsd-progsys/liquidhaskell/blame/develop/src/Language/Haskell/Liquid/Parse.hs#L1572-L1573 :) 

The below 

```
{-@ data FEnv where 
    FCons  :: { g:Int | False } -> FEnv @-}
```

is parsed with an empty body `Trace: [dataDeclBodyP] : data FEnv  [] =`
But if I put it in one line it is properly parsed. i.e., the below 

```
{-@ data FEnv where FCons  :: { g:Int | False } -> FEnv @-}
```
is parsed as `Trace: [dataDeclBodyP] : data FEnv  [] =
    | FCons :: forall . g : {g : Int | False} -> FEnv`

**Comment by ranjitjhala** [comment] 2020-10-10 15:23
Niki I am suspicious of this because the “lib” module is checked the right
way? It’s only the imported spec in client that is wrong

**Comment by ranjitjhala** [comment] 2020-10-10 15:24
Still you are right the parsing is strange!

Does the reading of imported specs use the parser?

**Comment by nikivazou** [comment] 2020-10-10 15:46
Correct... I cannot actually understand how the "lib" module is checked correctly, since by debugging the parser, I cannot understand how the `False` precondition is parsed. Let's give kosmikus some time in case he knows what is going on, otherwise, I will look deeper.

**Comment by ranjitjhala** [comment] 2020-10-10 16:15
Also suspicious: switching off the “reflection” flag makes it work
correctly ...

**Comment by kosmikus** [comment] 2020-10-12 06:54
Sorry, I've only just seen this.

Without having looked at the code yet, the problem with
```haskell
{-@ data FEnv where 
    FCons  :: { g:Int | False } -> FEnv @-}
```
is that it violates the layout rule, because `FCons` is not indented more than the `data`.

So this is probably being parsed in the same way as
```haskell
{-@ data FEnv where @-}
{-@ FCons  :: { g:Int | False } -> FEnv @-}
```

It should be ok to say
```haskell
{-@ data FEnv where
      FCons  :: { g:Int | False } -> FEnv @-}
```
Unfortunately, the subsequent line is probably parsing as a standalone type signature (note that multiple specs in a single block are now allowed), so that there's not actually a parse error from this.

I will verify this is actually the case.

But if so, I'm not sure what to do. LH is very liberal in which identifiers it accepts type signatures for. We could say a `data` with a `where` needs at least one constructor, but that'd be in contradiction to Haskell syntax.

**Comment by nikivazou** [comment] 2020-10-12 10:01
Thanks @kosmikus ! I also checked that with proper indentation the client is safe.

@michaelborkowski can you use the indentation there the data constructor definitions appear after the `d` of the `data` keyword to check that it addresses your problem?   

@kosmikus can we say that we can give type signatures only to identifiers that do not start with upper case? 
There are cases where we have refined data constructors, but we can restrict these cases only to explicit assumptions, e.g., 

The below should not get parsed:

```
{-@ FCons  :: { g:Int | False } -> FEnv @-}
```

while the below should get parsed:

```
{-@ assume FCons  :: { g:Int | False } -> FEnv @-}
```

Is this a feasible solution?

**Comment by kosmikus** [comment] 2020-10-12 12:18
@nikivazou That sounds like a plausible workaround to me. The rules for identifiers are somewhat complicated in LH right now, so I'm not sure if this will be without problems, but I can try.

**Comment by nikivazou** [comment] 2020-10-12 13:25
Thanks!!!

**Comment by kosmikus** [comment] 2020-10-12 14:39
@nikivazou We may have a similar pitfall for class declarations though ...

**Comment by kosmikus** [comment] 2020-10-12 15:13
@nikivazou One strange interaction I had not been aware of yet is that for `data ... where`, there's currently no new layout block being introduced for the constructors, and they're instead to be separated by `|` (even though we're using GADT-like syntax!). Would it in principle be ok to remove this and replace this with layout-only?

**Comment by ranjitjhala** [comment] 2020-10-12 15:39
Can anyone explain why the lib works as expected (the false is parsed) but
not the client?

**Comment by ranjitjhala** [comment] 2020-10-12 15:40
@kosmikus - yes this would be great; we (or was it me) added the | just due
to my ineptitude with parsing, would be great to get rid of it now!

**Comment by adinapoli** [comment] 2020-10-13 06:10
> Can anyone explain why the lib works as expected (the false is parsed) but
not the client?

I might be totally off track, but here is my guess: ~~the lib works because the `FEnv` is still parsed incorrectly, but it's not required to check the lib module, so LH doesn't choke. Conversely, when it times to verify the `client` , we need the refinement for `FCons`, and that's where things start to go wrong.~~. Ah, I take it back, both uses `FCons`. Maybe in one case LH has access to the _local_ definition and it doesn't have to somehow look at the wrongly-parsed refinement?

**Comment by kosmikus** [comment] 2020-10-13 06:14
More speculation from my side: I suspect LH allows providing a refinement type signature for a constructor in isolation, and uses it in the local module, but does not write it to the interface file subsequently. @adinapoli knows more about how the interfaces are constructed, though.

**Comment by nikivazou** [comment] 2020-10-13 08:35
@kosmikus I agree both with your speculation and that we should follow ghc's syntax if possible.

**Comment by kosmikus** [comment] 2020-10-13 12:43
For the parsing, we actually have multiple possibilities, with different trade-offs.

First, some terminology:

- A *faithful* implementation of the layout rule allows a new block to start only on a column that is strictly greater than the indentation column of the surrounding block. This corresponds to what Haskell implements in nearly all cases.

- A *relaxed* implementation of the layout rule allows a new block to start also on the same column as the surrounding block. Haskell implements this in the context of `NonDecreasingIndentation` for certain situations within `do` blocks.

It turns out that my implementation in LH is currently relaxed. This may have been partially deliberate, to get more existing programs to pass, but it's also possible that it is just an oversight. In any case, I did not clearly document this decision, which makes me assume the latter reason.

Furthermore, in the `data ... where` situation, everything following the `where` is currently *not* a new layout block, but as discussed above already, a sequence of constructors separated by `|`.

### Current status

For `data ... where`, because there's no new block after the `where`, the normal rules for a single declaration apply, and these are that subsequent lines must be indented more than the original line if they're supposed to belong to the same declaration. This is why we currently have a failure. The single constructor is not seen as part of the `data` declaration, but as a new declaration.

For `class ... where`, we *do* have a layout block after the `where`, and this means that we can actually parse
```haskell
{-@ class Foo a where
    foo :: a -> Int
    bar :: a -> Int
@-}
```
as a single class declaration, because the layout rule currently is *relaxed* (see above).

However, the relaxed interpretation comes with a problem. What if we *want* a subsequent type annotation to be interpreted as not being part of the class? We cannot escape the block except by using a construct that would not parse as a component of the block.

### Option: Make everything relaxed

One can argue that the "no escape" isn't that bad. After all, we can still choose to indent the methods of a class properly, and then we can escape. For historic reasons, having multiple spec declarations within a single `{-@ @-}` block is rare anyway. Fewer existing code will have to be edited.

So we could just switch `data ... where` to make use of layout and keep the layout rule relaxed. Then the example in this bug would also parse.

### Option: Make everything faithful

We could switch `data ... where` to make use of layout and change the layout rule to be faithful everywhere. Then the example in this bug would still cause problems, and *in addition*, the class example shown above would also cause potential problems, because it would now be parsed as an empty class and two standalone refinement type signatures.

@nikivazou suggested we could make the reading with the standalone constructor type signature for the `data` declaration illegal in another way, by allowing explicit constructor refinements only with `assume`. However, the class declaration would still be illlegal.

I think I would prefer to implement this solution and deal with the pitfalls in another way: It currently seems as if LH is doing relatively little sanity checking on the specs provided. For example, in
```haskell
{-@ data FEnv where 
    FCons  :: { g:Int | False } -> FEnv @-}

data FEnv = FCons Int
```
read as two separate spec declarations, we are giving a LH declaration for an empty type `FEnv`, even though the Haskell version of the type has a constructor. Should this be allowed? If it should be allowed, shouldn't it at least provoke a warning? A warning might be enough here to make the user understand there's a parsing problem.

Similarly, in the `class` declaration, should it be allowed to provide a class declaration that does not contain all methods that exist on the Haskell side? Or should it be a warning?

The above list is not necessarily exhaustive. There may be other, better solutions for all this.

**Comment by michaelborkowski** [comment] 2020-10-14 05:56
@nikivazou My mistake, this does work now! Thanks everyone!

<del>
If I fix the indentation, and make sure that both the constructors and the `|` characters are indented further to the right than `data`, that is

```
{-@ data FEnv where
        FEmpty :: FEnv
      | FCons  :: x:Vname -> t:FType -> { g:FEnv | not (in_envF x g) } -> FEnv
      | FConsT :: a:Vname -> k:Kind  -> { g:FEnv | not (in_envF a g) } -> FEnv @-}
```
<del>
then the definition will parse successfully, but the original issue still exists. The refinement on the function `simple` passes when in the same file as the constructor definition but fails when the identical `simple'` is in a different file:

https://github.com/michaelborkowski/liquidmeta_public/blob/master/FixedIndentationTest1.hs
https://github.com/michaelborkowski/liquidmeta_public/blob/master/FixedIndentationTest2.hs</del>

**Comment by nikivazou** [comment] 2020-10-14 06:39
I have a slight preference for the faithful implementation. 

For the relaxed, we can enforce that only one spec goes at each `{-@ ... @-}` block, but how will we handle the `.spec` files where there is no `{-@ ... @-}` separator? 

For the `class` definition, to me, it makes total sense to only refine some methods, as the rest (unrefined) ones will get the `true` type. Same for the data declarations: whatever is not refined is assumed to be true.

**Comment by kosmikus** [comment] 2020-10-14 07:04
@nikivazou So the result of the call yesterday was a bit different, but we can still discuss it again:

- Faithful layout rule.
- Require classes and datatypes to list all constructors / class methods even if they're not supposed to be refined, with the exception of a data declaration without constructors (and without `where`!) that is only used to attach a termination measure.
- Add a post-parsing check that errors out if datatypes / classes do not match the above requirement.

I personally believe that allowing constructors or type signatures to be omitted in datatype/class refinements is saving typing in the wrong place. If you evolve a datatype by changing its constructors, or adding new ones, I think it's helpful to be forced to adapt the refinement version if you have one. We could possibly still allow something like `Foo :: _` to denote that we "just" want the Haskell type. Of course, if we ever get to the point where the refined version becomes the definitive one, it also has to be complete for the Haskell version to be derivable from it.

A variant we discussed is to allow partial datatypes/classes, but to disallow "floating" constructor / class method refinements. I.e., if you're having a top-level refinement for a datatype constructor or a class method (at least one defined in the same module), that'd be considered wrong.

Somewhat unrelatedly, allowing multiple spec declarations in a `{-@ @-}` block was one of the reasons why we wanted the parser rewrite in the first place. I think it'd be sad if we'd just give this up again.

**Comment by nikivazou** [comment] 2020-10-14 07:25
Sounds good! 

My thinking in allowing partial specs for type class methods is mostly because of methods with default implementations. E.g., if you refine Monad, do you also have to refine the default `>>`? 
When I define a Monad instance I almost never define `>>`. But I can see why its refined type can be required. So, I agree with what you discussed.

**Comment by kosmikus** [comment] 2020-10-27 13:43
I've created #1788 for this. It still needs a little bit more work.

**Comment by facundominguez** [comment] 2024-05-30 13:54
I'm closing because the original question seems to have a resolution. But it would be ok to spin new issues from the discussion.

**Closed as completed by facundominguez** 2024-05-30 13:54 UTC
