### ISSUE TITLE
Need to explicitly import data constructor

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1394] opened 2019-01-16 20:29 UTC
[Related to #1393] 

When you have a "library" module 

```haskell
{-# LANGUAGE GADTs #-}
{-@ LIQUID "--reflection"  @-}

module IProp where

data FooP where
  Foo :: Int -> FooP

-- | The Predicate describing the closure of a relation
data Foo where
  Refl :: Int -> Foo

{-@ data Foo where
      Refl :: n:Int -> Prop (Foo n)
  @-}

-- Ind Pred Boilerplate
{-@ measure prop :: a -> b           @-}
{-@ type Prop E = {v:_ | prop v = E} @-}
```

and you then import it thus:

```haskell
module ICli where
import IProp
```

LH complains with 

```

 IProp.hs:11:3-20: Error: Illegal type specification for `IProp.Refl`

 11 |   Refl :: Int -> Foo
        ^^^^^^^^^^^^^^^^^^

     IProp.Refl :: n:GHC.Types.Int
                   -> {v : IProp.Foo | prop v == Foo n}
     Sort Error in Refinement: {v : IProp.Foo | prop v == Foo n##IProp.Refl}
     Unbound symbol Foo --- perhaps you meant: len, prop, v, snd, fst ?
```

(Probably) because of the `REBARE` refactor is such that the data-constructor 
name `Foo` is no longer anywhere in scope. The "workaround" is to just force GHC 
to actually put the name `Foo` (or more generally, the data constructor) into the 
scope for the client module by either writing:

```haskell
import IProp (FooP(..))
```

or just using the name somehow

```haskell
silly = Foo
```

**At the very least** we should think of a way to improve the error message to point here, or suggest an actionable fix e.g. 

```
If the missing name is an imported data constructor, then forcibly import ...
```

**Comment by adinapoli** [comment] 2020-10-26 13:14
@ranjitjhala using the latest `HEAD` I can't reproduce this anymore. Would you be able to try the testcase again at some point in the future and let me know? The general idea of "let's improve the error messages" is still valid methinks, I guess we just need a valid reproduction case to test its effects 😉

**Comment by facundominguez** [comment] 2024-06-02 17:34
Closing since I can't reproduce this with the latest LH.

**Closed as completed by facundominguez** 2024-06-02 17:34 UTC
Labels: bug, errormsg, modules, adt
