### ISSUE TITLE
Another reflect/measure import issue

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1104] opened 2017-09-29 18:01 UTC
@jprider63 discovered another interesting import bug. See [here](https://github.com/ucsd-progsys/liquidhaskell/commit/501ecf27d4f4fc44ddac8d5c0290f2329218a76b).

If I define a measure in `isFoo` in `AA` 
```
module AA where 

data Foo a b = Foo {fooA :: a, fooB :: b}  |  Bar

{-@ measure isFoo @-}
isFoo :: Foo a b -> Bool
isFoo (Foo _ _)= True 
isFoo Bar = False 
```

Then I cannot prove that the Haskell `isFoo x` satisfies the `isFoo` logical predicate in sa **different** module. That is the following fails

```
import AA

{-@ lazy bar @-}
-- bar is UNSAFE 
{-@ bar :: Foo a b -> {v:Foo a b | isFoo v} @-}
bar :: Foo a b -> Foo a b
bar x | isFoo x  = x 
bar x = bar x 
```

But the above is safe when 
 - `isFoo` is defined as a measure (or reflect) in the same module and
- `isFoo` is defined as a reflect (instead of measure)

**Comment by ranjitjhala** [comment] 2017-10-03 23:31
Looks like the "singleton" type for the measure `isFoo` is getting lost in the import, perhaps because  saveLiftedSpec runs *before* the strengthening happens?

**Comment by ranjitjhala** [comment] 2017-10-04 03:32
should be fixed by upcoming T1089 PR

**Comment by nikivazou** [comment] 2017-10-04 19:08
@jprider63, can you check is this solves our problem? 

(Will not have time to check it this week)

**Comment by jprider63** [comment] 2017-10-04 20:31
What is T1089 PR? I can test it if it's a branch I can build.

**Comment by ranjitjhala** [comment] 2017-10-04 20:32
About to submit PR for develop, will ping you when done :)

**Comment by jprider63** [comment] 2017-10-04 20:33
Sounds good!

**Closed** 2017-10-05 04:33 UTC
Labels: fixed?

**Comment by ranjitjhala** [comment] 2017-10-05 04:54
Should be fixed in develop, let me know if thats not the case! Thanks!

**Comment by jprider63** [comment] 2017-10-05 07:04
Unfortunately, I'm getting an error with develop (527a5cc2adf68b080a087a838d2984c0b5f6fa99). Here is [the log](http://lpaste.net/5277827109505466368).

**Comment by ranjitjhala** [comment] 2017-10-05 11:48
Are you sure you rebuilt first? There are things in the log that are not
printed out now e.g.
The lines that say "makeRecordSelectorSigs"

https://github.com/ucsd-progsys/liquidhaskell/commit/527a5cc2adf68b080a087a838d2984c0b5f6fa99#diff-4b81a188ab3ccd6a62c2c91080b5438dR448

**Comment by ranjitjhala** [comment] 2017-10-05 12:00
​Ignore previous comment! 

I can't reproduce your error (as I don't have the code).

The code that @ni​kivazou points out definitely works on `develop` now, see 

   tests/import/lib/T1104_{AA, BB}.hs

This may be something else? Just from the log, I see there is a `Pair` 
constructor and a `pFst` and `pSnd` which makes me suspect this 
is the same issue as the one I uncovered last night:

https://github.com/ucsd-progsys/liquidhaskell/issues/1109

**Comment by ranjitjhala** [comment] 2017-10-05 12:30
Btw, this is going to take a while to fix I'm afraid, so it may be a 
good idea for you to use an earlier version without the ADT stuff,
e.g. the `popl18` branch?

**Comment by nikivazou** [comment] 2017-10-05 16:06
He is definitely rebuilding everything (because he has a make command that rebuilds everything) 

@jprider63 , I suggest you keep the older version that does not crash your code with the manually annotated hack for the imported method. 

```
isFoo :: x:Foo a b -> {v:Bool | v == isFoo x}
```

I will take a look next week to simplify your error and create another issue for @ranjitjhala to fix :)
Thanks!!!

**Comment by jprider63** [comment] 2017-10-05 16:22
I believe everything should be rebuilt. I pulled develop, checked out submodules, and did a stack install. Then I deleted my .liquid directory and ran make as you saw. 

No problem! I'll do as Niki suggests.
