### ISSUE TITLE
PLE - elaborate makeKnowledge error

### ISSUE THREAD

**Issue by morteako** [ucsd-progsys/liquidhaskell#1483] opened 2019-04-30 23:00 UTC
Hi. I have come across a weird error (at least to me).

Full code : https://gist.github.com/morteako/97c67425a191052229c57d7a54547bba#file-splittree-hs

It is this function that is the culprit:
```
{-@ reflect deepL @-}
{-@ 
deepL ::  (v -> v -> v) -> v ->  (a -> v) -> {v:[a] | len v <= 4 } -> m:FingerTree v (Node v a) -> Dig a -> z:{v:Int | v = 1} -> FingerTree v a / [ftDigsize m, z]
@-}
deepL ::  (v -> v -> v) -> v ->  (a -> v) -> [a] -> FingerTree v (Node v a) -> Digit a -> Int -> FingerTree v a
deepL ap e mes [] m sf _ = case viewL ap e (measureNode ap e mes) m 0 of
    NilL -> Empty
    ConsL a m' -> deep ap e mes (nodeToList a) m' sf
deepL ap e mes (p:pr) m sf _ = deep ap e mes (p:pr) m sf
```

When I try to run liquidhaskell on this , I get 800 lines of "elaborate makeKnowledge"++. Full Error: https://gist.github.com/morteako/97c67425a191052229c57d7a54547bba#file-lherror

What is weird to me is that it seems like it the combination of the viewL, and the 2 deep calls that seems to be the problem, and not the individual calls.
If I remove one of the deep calls, it works fine, or if I remove the viewL call it also works.
Also changing (p:pr) to un (where un is basicly the same as undefined, un = un), makes it safe.
Changing (nodeToList a) to un does not help.
These 2 versions compiles
```
deepL ap e mes [] m sf _ = case NilL of
    NilL -> Empty
    ConsL a m' -> deep ap e mes (nodeToList a) m' sf
deepL ap e mes (p:pr) m sf _ = deep ap e mes (p:pr) m sf

deepL ap e mes [] m sf _ = case viewL ap e (measureNode ap e mes) m 0 of of
    NilL -> Empty
    ConsL a m' -> deep ap e mes (nodeToList a) m' sf
deepL ap e mes (p:pr) m sf _ = deep ap e mes un m sf```

Any idea?

**Comment by morteako** [comment] 2019-06-19 11:53
I realized that the gist I linked was not sufficient to replicate the problem, because you needed 2 files I forgot to include. Sorry

https://github.com/morteako/liquid-haskell-error/blob/master/viewProofs.hs
Here is a self contained file.
This gives the error uploaded here : https://github.com/morteako/liquid-haskell-error/blob/master/error.txt

It still does not work.

I have tested 
LiquidHaskell Version 0.8.6.0, Git revision ade1777fd8ecbe5911bcc559f719fffc18c95c42 (dirty) [develop@ade1777fd8ecbe5911bcc559f719fffc18c95c42 (Sat Jun 15 07:51:54 2019 -0700)]
and also
LiquidHaskell Version 0.8.6.0, Git revision 96efa831a80403b1b7740a56d1a1690a24f5d9af [develop@96efa831a80403b1b7740a56d1a1690a24f5d9af (Wed Jun 12 07:59:43 2019 +0200)]

**Comment by ranjitjhala** [comment] 2019-06-19 13:54
Oops sorry I missed this the first time around will take a look!

**Comment by ranjitjhala** [comment] 2019-06-19 20:52
Hi @morteako -- I think I know what the problem is -- the polymorphic recursion inside the finger-tree type is breaking some assumptions made in the `makeKnowledge` (which is creating some ill-sorted 
refinements) I think we can make the latter a bit more fine-grained (to discard ill-sorted knowledge not crash) which should fix your problem. Will try to fix in a day or two!

**Comment by ranjitjhala** [comment] 2019-06-20 19:55
Dear @morteako,

hmm. Unfortunately, I really don't follow this bug -- it is due to some _very_ subtle interaction of the 
polymorphic recursion used by `FingerTree` and the `--ple` feature. In essence PLE does a "type level computation" but is somehow generating ill-typed terms (which is what triggers the crash.)

I am planning to rewrite the PLE code (for various reasons) and hopefully will be able to better understand
what is going on here then. However, in the short term -- I suggest:

1. Disable `--ple` (remove that line, or replace it with `--ple-local`)
2. If you need PLE to simplify equational proofs, then you can enable it "locally" at individual proofs, by writing `{-@ ple foo_lemma @-}` where you want to use `ple` inside `foo_lemma`, for example as shown here: https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/ple/pos/T1382.hs#L56-L61

With these, your code passes if you additional strengthen the type of 

```haskell
{-@ nodeToList :: _ -> {v:_ | 1 <= len v && len v <= 4} @-}
```

Sorry to not have better news, but will get back to this after a few pressing deadlines!

**Comment by facundominguez** [comment] 2024-06-02 02:18
I'm closing this since the code to reproduce it is not available. But please, feel free to reopen it if the test case can be reconstructed.

**Closed as completed by facundominguez** 2024-06-02 02:18 UTC
