### ISSUE TITLE
Unsound: LH checks incorrect program with diverging value

### ISSUE THREAD

**Issue by lbartl** [ucsd-progsys/liquidhaskell#1903] opened 2021-11-11 12:36 UTC
I read the *Refinement Types For Haskell, ICFP 2014* paper and came up with a similar example that uses a diverging value:
```haskell
{-@ lazy diverge @-}
{-@ diverge :: {v:a | false} @-}
diverge = diverge

{-@ false_precond :: {v:a | false} -> Int -> {v:Int | v > 0} @-}
false_precond :: a -> Int -> Int
false_precond _ y = y

explode :: Int -> Int
explode x = x `div` false_precond diverge 0
```

LH checks that program and marks it as SAFE, but it is incorrect:
```haskell
> explode 1
*** Exception: divide by zero
```

The following may be related:
The paper says that this `test_collatz` function cannot be verified (though it is correct):
```haskell
{-@ lazy collatz @-}
{-@ collatz :: Pos -> {v: Int | v == 1} @-}
collatz :: Int -> Int
collatz 1 = 1
collatz n
  | even n    = collatz $ n `div` 2
  | otherwise = collatz $ 3*n + 1

test_collatz = let x = collatz 10 in 12 `div` x + 1
```
But LH checks it and marks it as SAFE.

**Comment by ranjitjhala** [comment] 2021-11-11 14:47
Hi @hanswurst862 -- this is not a bug: the `lazy` annotation means "all bets are off" (kind of like `unsafe` blocks in rust). 
So yes, if you have a binder like that in scope then you will be able to "prove" all sorts of spurious things, as essentially, you have "assumed" a contradiction to begin with.

**Comment by lbartl** [comment] 2021-11-11 14:54
@ranjitjhala Thanks for your answer.

I had a different understanding of `lazy`. According to the paper:
> The lazy keyword deactivates termination checking, and marks the output as a Div type.

I had the understanding that this means that one should use `lazy` for non-terminating functions and LH will respect that and will not „prove“ „spurious things“ because it marks the output as a Div type (like explained in the paper).

If this is not the case (lazy = unsafe), then how should one safely annotate functions that do not terminate?

**Comment by ranjitjhala** [comment] 2021-11-11 14:57
Ah yes, very good (let me reopen so we fix it). 
We jettisoned the `Div` stuff as it was _super_ rare, 
complicated the code. Instead, its just simpler to eyeball 
in the rare cases that you use `lazy` that there are 
no (output) refinements. 

So effectively right now with `lazy` the semantics are only:

(1) termination checking is disabled all bets are off

Now you have two choices: to be on the safe side you can 

(2) make sure there are no output refinements on lazy term

or if you are confident that the code is in fact terminating 
and you need an escape hatch you can add the refinements 
too.

I suppose it may make sense to have a `strict` or `safe` mode
which specifically checks (2).

**Comment by lbartl** [comment] 2021-11-11 15:29
Ok, so basically the paper is old news?

I don't think (2) is sufficient. This code does not use output refinements on lazy terms, is incorrect and LH says it's safe:
```haskell
{-@ lazy diverge @-}
diverge :: a
diverge = diverge

{-@ false_precond :: {v:a | false} -> Int -> {v:Int | v > 0} @-}
false_precond :: a -> Int -> Int
false_precond _ y = y

explode :: Int -> Int
explode x = x `div` false_precond diverge 0
```

**Comment by ranjitjhala** [comment] 2021-11-11 16:17
Aha yes @nikivazou favorite polymorphic instantiation issue :-)
(That introduces refinements at instantiation - that too must be stopped
for lazy functions - at least in a “strict” or “safe” mode)

**Comment by nikivazou** [comment] 2021-11-15 15:20
For me too, the `lazy` or `no-termination` annotations means potential unsoundness. 
In the ICFP'14 paper  we have ways to address this (1) do not allow refinementments on potential diverging expressions and 2) via the label mechanism we propose) but the code that implemented these did not survive...

**Comment by yanhasu** [comment] 2021-11-22 16:07
On [the current demo](http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1637596937_657.hs), `lazy` seems to postulate finite return type ('`Fin` type') as well eventual reduction to WHNF ('`Wnf` type').

So I'm guessing that `Wnf` has been jettisoned as well as `Div`, and now `Fin` is all that's left?

**Comment by facundominguez** [comment] 2024-05-28 18:44
I'm closing since the initial example seems to be clarified. Still, it is unclear to me if further action would be wanted. In that case, I suggest starting a new issue.

**Closed as completed by facundominguez** 2024-05-28 18:44 UTC
