### ISSUE TITLE
Error reported for non-holes

### ISSUE THREAD

**Issue by ranjitjhala** [ucsd-progsys/liquidhaskell#1465] opened 2019-04-19 03:06 UTC
@nikivazou I think you added this "holes" feature? The following code:

```haskell
{-@ incr :: Nat -> Nat @-}
incr :: Int -> Int
incr _x = _x + 1
```

returns the peculiar "error"

```
**** RESULT: UNSAFE ************************************************************

 /Users/rjhala/research/stack/liquidhaskell/tests/todo/NotHole.hs:3:11-12: Error: Hole Found
 _x :: GHC.Types.Int
```

which is puzzling because `_x` is just a plain binder and not, in fact, a hole.

Can you fix this please? I suspect you need to use some better test from 
the GHC API for whether a binder is a hole or not -- than just whether it starts with `_` ?

**Comment by nikivazou** [comment] 2019-04-19 09:39
Good point!

@Tritlo do you know if I can get the hole variables from `ModGuts` or a similar ghc environment? 

I did some searching and could not find that info.  Worst case we can reproduce it by checking what generates a "Hole found" ghc error.

**Comment by Tritlo** [comment] 2019-04-19 12:25
I think the check is simply to see whether the identifier `_x` is in scope, and treat it as a hole if not.

**Comment by nikivazou** [comment] 2019-04-19 13:44
Sadly this does not work, because we are analyzing Corebinds, where the `_x` is defined (i.e., it is in scope) to throw an error at runtime.

**Comment by Tritlo** [comment] 2019-04-19 14:33
Right. Should it be doing that? I might be misunderstanding, but I'd think that the right behaviour in this case, if it is in scope, is to *not* throw an error.

**Comment by ranjitjhala** [comment] 2019-04-19 14:36
I think he means only treat unbound vars as holes?

**Comment by nikivazou** [comment] 2019-04-19 14:47
There are no unbound variables in the desugared module (we get the module after type checking). 

Consider this hole: 

```
incr x = _incr
```

After desugaring we will get something like this in core
```
incr x = let _incr = error "Hole found" in _incr
```
But this `_incr` was *initially* a hole, for while valid instances are generated.

The question is goes ghc keep track of the variables that were holes at user level?

**Comment by ranjitjhala** [comment] 2019-04-19 15:08
Got it thanks!  Would it help to ping Simon? Maybe after digging a bit...

**Comment by nikivazou** [comment] 2019-04-19 15:18
If Matti does not know, we can first ask whoever merged the holes PR, because Simon.

I did some digging and did not find anything :(

**Comment by nikivazou** [comment] 2019-04-22 09:25
@bgamari could you maybe help us with this issue? 

LH is analyzing Core and at that point it cannot tell while (value) variables were introduced as holes. 
Is there some ghc environment (maybe `ModGuts`, `ModIface`, etc) that stores the variables produced by user-defined holes? 

Thanks!

**Comment by ranjitjhala** [comment] 2019-05-09 05:26
@nikivazou for now, I am guarding this under a flag `--typed-holes` because `_x` etc. is a perfectly legitimate binder name, and its odd to see strange errors. c.f. PR #1481

**Closed as completed** 2019-05-10 16:05 UTC
