### ISSUE TITLE
Spec File Ignored

### ISSUE THREAD

**Issue by jswrenn** [ucsd-progsys/liquidhaskell#728] opened 2016-06-07 16:02 UTC
Let's say I have some library file, Library.hs, that I do not want to verify:
```Haskell
module Library (foo) where
foo a = a
```

A spec for that library file, Library.spec, with a time-bomb refinement:
```Haskell
module Library (foo) where
foo :: a:{v:t | false} -> t
```

And a client which I would like to verify using LiquidHaskell:
```Haskell
module Client where
import Library
bar = foo 1
```

All of these files are in a folder called `toyprogram`. Running `liquid -i toyprogram  toyprogram/Client.hs` reports `SAFE`, but I expect it to report `UNSAFE` (as it does if all three files are combined into one file).

This seems related to feature request #274, but the comments there indicated that this is already implemented. Am I missing something?

**Comment by sorawee** [comment] 2016-06-07 16:50
When I run these, I get an error, saying that the first line of `Library.spec` should be `module spec Library where`. However, after fixing that, it reports SAFE. At least, we know that the spec file is examined, but it doesn't give the expected result somehow...

**Comment by ranjitjhala** [comment] 2016-06-10 17:16
@spinda -- the above is happening because of this line:

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/GHC/Interface.hs#L460

Why do we do it? What would break if we removed such filtering?

**Comment by ranjitjhala** [comment] 2016-06-10 17:48
Hmm. This is tricky. In short, the `.spec` files are really meant for modules _without_ code:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/README.md#modules-without-code

Allowing them for modules with code (esp. "home modules", which are roughly, those in the package
currently being checked), opens the door to conflicting specifications. e.g. when checking `text` we get
duplicate specification errors from `Data/Text/Common.hs` and `Data/Text/Common.spec`.

One could try to prioritize one over the other (*code* over *spec*), but perhaps its simpler and 
cleaner to stick with `.spec` for modules without code? Thoughts?

**Comment by ranjitjhala** [comment] 2016-06-10 18:03
@jswrenn instead for your use case, does the following work:

`Lib.hs`

```
module Lib (foo) where

foo a = a
```

(instead of a .spec file, just use a haskell module -- `LibSpec.hs`)

```
module LibSpec ( module Lib ) where 

import Lib

{-@ Lib.foo :: {v:a | false} -> a @-}
```

and then here's `Client.hs`

```
module Client where

import Lib          -- use this if you DONT want the spec  
import LibSpec  -- add this (or replace the above) if you DO want the spec

bar = foo 1
```

**Comment by ranjitjhala** [comment] 2016-06-10 18:07
I should add that if you do the above then LH properly reports the warning.

Folks, can we just use the above to "simulate" the separate specs (for home modules?)

**Comment by ranjitjhala** [comment] 2016-06-10 19:56
Closing as feature-not-bug (unless prodded otherwise).

**Closed by ranjitjhala** 2016-06-10 19:56 UTC

**Comment by sorawee** [comment] 2016-06-10 20:02
Ah, I think I misunderstood the meaning of "module WITHOUT code" -- it doesn't mean that the spec file doesn't have code. Rather, it means the whole module doesn't have code...

**Comment by ranjitjhala** [comment] 2016-06-10 20:11
Yes, e.g. `Prelude` or some random external module that you might import
(e.g. Vector, or Control.Applicative etc.)

Will clarify in README!

**Comment by spinda** [comment] 2016-06-16 08:33
@ranjitjhala Sorry, was sucked into finals and traveling earlier. Are you sure that line is the cause? That only filters out specifications from *quasiquoters* that aren't in the current module.

I believe it's this line that's actually filtering out .spec files for which we have .hs files: https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/GHC/Interface.hs#L494

**Comment by ranjitjhala** [comment] 2016-06-16 17:51
No this is a subtler issue -- see discussion above...
