### ISSUE TITLE
[plugin] Undeclared type-variable error not properly reported for GHC to render as a compilation error

### ISSUE THREAD

**Issue by plredmond** [ucsd-progsys/liquidhaskell#1711] opened 2020-07-20 22:25 UTC
In this example `Bool` is typo'd to `bool`, which is an undeclared/out-of-scope type variable. LH correctly identifies this error, but doesn't report it properly when LH is used as a GHC plugin. As a result, third party tools which integrate with GHC cannot detect the error condition. [In slack](https://liquidhaskell.slack.com/archives/C54QAL9RR/p1595280783112400?thread_ts=1595280231.110000&cid=C54QAL9RR) @ranjitjhala said, "we should trap these too" and suggested @adinapoli.
```haskell
{-@ bad :: {v:bool | v} @-}
bad = False
```

Expected behavior:
* Error is reported via GHC in a way that third-party programs (eg. GHCID) can detect.

Actual behavior:
* Error isn't reported via GHC in a way that third-party programs can detect.

--- 

Versions in use:
* `liquidhaskell@26cad4f`, `liquid-fixpoint@a4e303b`

**Comment by plredmond** [comment] 2020-07-20 22:58
Here's another example of this sort of problem, though I don't know whether this generates the exact same kind of error as the first:
```haskell
ax1 :: Integral a => a -> Bool
{-@ ax1 :: Int -> TRUE @-}
ax1 x = x < x + 1
```
This shows a human-readable "does not refine Haskell type" error when you build, but third-party tools like GHCID cannot see the error.

**Comment by plredmond** [comment] 2020-07-21 00:54
Here's a third example. This produces a "multiple specifications for .." error when you build, but third party tools like GHCID cannot see the error.

```haskell
{-@ i7 :: { i : Int | i == 6 } @-}
{-@ i7 :: { i : Int | i >= 0 } @-}
{-@ i7 :: { i : Int | i <= 10 } @-}
{-@ i7 :: { i : Int | i >= 0 && i <= 10 } @-}
{-@ i7 :: Int @-}
i7 :: Int
i7 = 6
```

This example is actually lifted directly from [a tutorial](https://liquid.kosmikus.org/) linked from the [LiquidHaskell homepage](http://ucsd-progsys.github.io/liquidhaskell/), so it's a little strange that it causes an error.

**Comment by adinapoli** [comment] 2020-07-21 06:47
@plredmond Thanks for taking the time to write this ticket!

@plredmond @ranjitjhala I confess I haven't look too deeply into this issue, but having spent a fair amount of time on LiquidHaskell's internals, I'll have a guess: I think the culprit is that _not all_ (parsing, or otherwise) errors are correctly routed through the error-handling mechanism we put in place for the plugin, which uses the GHC API to log any warning or error so that tools like `ghcid` and `ghcide` could correctly interpret it.

Part of the problem is that the parser's code has a bit of rough edges (but luckily we have @kosmikus 's patch which will fix that) but also that some functions throws exceptions from pure code (see for example `extractSpecComment`).

I would suggest that if the fix is easy in this case, we go for it (and I will take a look later today) but if we find like we are just hitting the tip of the iceberg, perhaps it would have more sense to wait for @kosmikus 's patch to be merged and then perhaps redesign the error-handling, if not from the ground up in a way that prevents all the different permutations of these errors to crop up?

**Comment by adinapoli** [comment] 2020-07-21 09:21
I have reproduced the first example and indeed there are two things going wrong here:

1. The parser should arguably catch this as a parsing error, so that we fail preemptively;
2. In the current codebase, this misbehave due to the fact `plugHoles_old` throws an exception (from pure code).

Ditto for the second and third example, with exceptions being thrown in different parts of the codebase. I wonder if we could jerry-rig this for now by using `try` and `evaluate` in the plugin for now, before venturing in a more pervasive refactoring.

**Closed as completed** 2020-07-21 13:39 UTC

**Comment by ranjitjhala** [comment] 2020-07-21 15:00
Your plan sounds good to me @adinapoli Thanks!!

**Comment by plredmond** [comment] 2020-09-18 21:28
@adinapoli FYI there's another instance of this bug in #1758, example (2).
