### ISSUE TITLE
Refinements in infix instance methods are ignored

### ISSUE THREAD

**Issue by nikivazou** [ucsd-progsys/liquidhaskell#1126] opened 2017-10-11 14:48 UTC
See [tests/todo/T1126.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/7ccafa82eb705fb08208f3c080042a88e22f8381/tests/todo/T1126.hs).

```
-- This is SAFE 
unsound x y = x ==. y

-- This creates a type error 
ok      x y = x `cmp` y 
```

Where both `(==.)` and `cmp` are instance methods with exactly the same refinements that require that their arguments are equal.

The methods are defined as follows:

```
class OptEq a where
  (==.) :: a -> a -> a

instance OptEq a where
{-@ instance OptEq a where
  ==. :: x:a -> y:{a| x == y} -> a
  @-}
  (==.) x _ = x
```

and 
```
class OptEq2 a where
  cmp :: a -> a -> a

instance OptEq2 a where
{-@ instance OptEq2 a where
  cmp :: x:a -> y:{a| x == y} -> a
  @-}
  cmp x _ = x
```

**Comment by ranjitjhala** [comment] 2017-10-11 16:59
wow... on the positive side, probably easy to fix ... once you figure out what the problem is :)

**Comment by nikivazou** [comment] 2017-10-11 17:37
Yes, I assume the infix methods get different names? Should not be very difficult to fix

**Comment by nikivazou** [comment] 2017-10-14 16:54
Some progress: it is not about infix, it is about the `.`. Specifically `dropModuleNames` in https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/GHC/Misc.hs#L579

is wrong: `dropModuleNames("Main.==.") = ""`

**Comment by ranjitjhala** [comment] 2017-10-14 17:00
Aaargh...

**Comment by nikivazou** [comment] 2017-10-14 17:08
Oh @ranjitjhala well, I planned to "fix" dropModuleNames via conversion from Symbol to String, because the Symbol manipulation code is too complicated....  do you want to give it a try instead?

That is drop only the "ModuleName.": starting with capital character and finishing with `.`

**Comment by ranjitjhala** [comment] 2017-10-14 20:00
Sure leave it for me.

**Comment by ranjitjhala** [comment] 2017-11-02 03:51
@nikivazou is this fixed now? `tests/todo/T1126.hs` says UNSAFE?

**Comment by ranjitjhala** [comment] 2017-12-06 07:29
Am closing this as the tests do the right thing. LMK if we need to reopen?

* https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/T1126.hs
* https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/neg/T1126.hs

**Closed by ranjitjhala** 2017-12-06 07:29 UTC
Labels: bug, easy, fixed?, unsoundness
