### ISSUE TITLE
Can't refine recursive datatypes without ARs

### ISSUE THREAD

**Issue by yanhasu** [ucsd-progsys/liquidhaskell#1856] opened 2021-07-15 13:40 UTC
LH refuses to refine custom data types which both:
* Are recursive (e.g. lists)
* Don't explicitly bind abstract refinements

e.g.:
```
module Data' where


{-@ data Maybe' a = Nothing' | Just' a @-}
data Maybe' a = Nothing' | Just' a
-- OK

{-@ data IntStream' <p :: Int -> Bool> = Stream' (Int<p>) (IntStream' <p>)@-}
data IntStream' = Stream' Int (IntStream')
-- OK

{-@ data IntStream = Stream Int IntStream@-}
data IntStream = Stream Int (IntStream)
-- Not OK:
--    • Bad Data Specification
--GHC and Liquid specifications have different numbers of fields for `Data'.Stream`
```
([in the online demo](http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1626356097_37198.hs))

**Comment by ranjitjhala** [comment] 2021-07-15 14:25
Oops this is a parser bug - fortunately it is easy to fix by adding fields to the Liquid spec. See

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1626358992_37207.hs

**Comment by curiousleo** [comment] 2021-11-15 08:27
The relevant toplevel parser definition appears to be here:

https://github.com/ucsd-progsys/liquidhaskell/blob/5c43f227c79d477bf0ca9db3a4b538bfad296b67/src/Language/Haskell/Liquid/Parse.hs#L1125

It leads via `dataDeclP` -> `dataDeclBodyP` -> `dataCtorsP` -> `dataConP` to `dataConFieldsP`.

`dataConFieldsP` defines two alternatives: `explicitCommaBlock`, which looks like it ought to parse stuff like `{ zz :: Int, yy :: IntStream}`, and `many dataConFieldP`, which looks like it should parse something like `Int IntStream`.

**Comment by curiousleo** [comment] 2021-11-15 08:31
The error message itself originates here: https://github.com/ucsd-progsys/liquidhaskell/blob/5c43f227c79d477bf0ca9db3a4b538bfad296b67/src/Language/Haskell/Liquid/Bare/Plugged.hs#L89

This suggests that parsing succeeds, but the number of fields is not 2? This is a good starting point for a bit of testing / debugging.

**Comment by curiousleo** [comment] 2021-11-15 09:06
The parser output contains the two fields in both cases:

```
λ> let pos = Text.Megaparsec.Pos.initialPos "<unknown>"
λ> let nobraces = Language.Haskell.Liquid.Parse.singleSpecP pos "data IntStream = Stream Int IntStream"
λ> let braces = Language.Haskell.Liquid.Parse.singleSpecP pos "data IntStream = Stream { zz :: Int, yy :: IntStream}"

λ> let (Right (DDecl ddecl)) = nobraces in let (Just [dcons]) = tycDCons ddecl in dcFields dcons
[("lq_tmp$db##0",Int),("lq_tmp$db##1",IntStream)]
λ> let (Right (DDecl ddecl)) = braces in let (Just [dcons]) = tycDCons ddecl in dcFields dcons
[("zz",Int),("yy",IntStream)]
```

**Comment by curiousleo** [comment] 2021-11-15 10:06
I just took a step back to try to reproduce this error at the `liquid` executable level, and I can't. Is it possible that http://goto.ucsd.edu:8090/index.html is running an ancient version of Liquid Haskell?

Here is what I tried:

```console
$ cat test.hs
{-@ data IntStream = Stream Int IntStream @-}
data IntStream = Stream Int IntStream

main :: IO ()
main = putStrLn "hi"

$ liquid test.hs

**** LIQUID: SAFE (0 constraints checked) **************************************
```

Tested with 4c1328f4bcfd52f50e8f2cca211a32f73ab7d03b (the last commit before July 15th) and on current `develop` at 5c43f227c79d477bf0ca9db3a4b538bfad296b67.

As a sanity check, I changed `{-@ data IntStream = Stream Int IntStream @-}` to `{-@ data IntStream = Stream Int @-}`, leading, as expected, to:

```
**** LIQUID: ERROR  ************************************************************
/home/leo/Code/liquidhaskell/test.hs:1:10-18: error: 
    Bad Data Specification
    GHC and Liquid specifications have different numbers of fields for `Main.Stream`
```

So ... all's well as far as I can tell.

@ranjitjhala or @nikivazou, do you know which version (ideally which commit) of Liquid Haskell is running at http://goto.ucsd.edu:8090/index.html?

**Comment by facundominguez** [comment] 2021-11-15 10:43
Prefixing a module with `{-@ LIQUID "--version" @-}` produces a log output containing
```
LiquidHaskell Version 0.8.6.0, Git revision 1d8c11324bb718eb3bd5c41643ba4b1cc377abf2 (dirty) [develop@1d8c11324bb718eb3bd5c41643ba4b1cc377abf2 (Thu Jul 11 14:48:47 2019 -0700)] 
Copyright 2013-19 Regents of the University of California. All Rights Reserved.
```

**Comment by curiousleo** [comment] 2021-11-15 11:03
Thanks @facundominguez!

> Thu Jul 11 14:48:47 2019

Wow, that _is_ old.

---

AFAICT this ticket is resolved: the issue appears to be fixed on `develop`.

A good follow-up would be to update the version of LH running at http://goto.ucsd.edu:8090/index.html.

**Closed as completed** 2021-11-15 15:02 UTC
