### ISSUE TITLE
Problem with unfolding when trying to prove a theorem

### ISSUE THREAD

**Issue by CodePeters** [ucsd-progsys/liquidhaskell#1315] opened 2018-05-08 20:23 UTC
The current code:

{-@ measure lElems @-}
lElems :: (Ord a) => List a -> S.Set a
lElems Nil         = S.empty
lElems (Cons x xs) = S.union (S.singleton x) (lElems xs)

{-@ reflect permutation @-}
permutation :: (Ord a) => List a -> List a -> Bool
permutation xs ys = lElems xs == lElems ys

{-@ select :: (Ord a) => a -> l1: List a -> (a, l2: {List a | llen l2 == llen l1 } ) @-}
select :: (Ord a) => a -> List a -> (a, List a)
select i  Nil        = (i, Nil)
select i (Cons x xs) 
    | i <= x    =  (j2, (Cons x l2))  
    | i > x     =  (j1, (Cons i l1))  
                       where (j1, l1) = (select x xs) 
                             (j2, l2) = (select i xs)              
                                          

selSort :: (Ord a) => List a -> List a
selSort  Nil        = Nil
selSort (Cons x xs) = (Cons j (selSort l))  
  where (j, l) = (select x xs)

{-@ thmPermProp1 :: xs:_ -> {permutation xs xs} @-}
thmPermProp1:: (Ord a) => List a -> Proof
thmPermProp1 Nil = trivial 
thmPermProp1 (Cons _ xs) = thmPermProp1 xs

{-@ thm_select_perm:: (Ord a) => l: List a -> x: a -> { permutation (Cons x l) (Cons (fst1 (select x l)) (snd1 (select x l ))) }  @-}
thm_select_perm:: (Ord a) => List a -> a -> Proof
thm_select_perm Nil x         
            =   permutation (Cons x Nil) (Cons (fst1 (select x Nil)) (snd1 (select x Nil )))
            ==. permutation (Cons x Nil) (Cons (fst1 (select x Nil)) (snd1 (select x Nil )))
            ==. permutation (Cons x Nil) (Cons (fst1 (x, Nil)) (snd1 (x, Nil )))
            ==. permutation (Cons x Nil) (Cons x Nil)    
            ==. True                                    
            *** QED
thm_select_perm (Cons y ys) x = trivial

The error liquid Haskell outputs:

Error: Liquid Type Mismatch

 116 | thm_select_perm Nil x
       ^^^^^^^^^^^^^^^

   Inferred type
     VV : {v : () | v == Language.Haskell.Liquid.ProofCombinators.trivial}

   not a subtype of Required type
     VV : {VV : () | Sort.permutation (Sort.Cons x ?a) (Sort.Cons (Sort.fst1 (Sort.select x ?a)) (Sort.snd1 (Sort.select x ?a)))}

   In Context
     x : a

     ?a : {?a : (List a) | Sort.llen ?a >= 0}

 /Users/georgepetrou/Desktop/newAttempt/selsort.hs:(117,17)-(122,19): Error: Liquid Type Mismatch

 117 |             =   permutation (Cons x Nil) (Cons (fst1 (select x Nil)) (snd1 (select x Nil )))
 118 |             ==. permutation (Cons x Nil) (Cons (fst1 (select x Nil)) (snd1 (select x Nil )))
 119 |             ==. permutation (Cons x Nil) (Cons (fst1 (x, Nil)) (snd1 (x, Nil )))
 120 |             ==. permutation (Cons x Nil) (Cons x Nil)     
 121 |             ==. True
 122 |             *** QED

   Inferred type
     VV : ()

   not a subtype of Required type
     VV : {VV : () | Sort.permutation (Sort.Cons x ?a) (Sort.Cons (Sort.fst1 (Sort.select x ?a)) (Sort.snd1 (Sort.select x ?a)))}

   In Context
     x : a

     ?a : {?a : (List a) | Sort.llen ?a >= 0}

I can't understand why?? I have fully unfold the definitions but still solver is unable to solve the simple case where input list is Nil. I suspected than maybe solver couldn't deduct that permutation (Cons x Nil) (Cons x Nil) is true so I even tried using thmPermProp1 in order to prove that :

{-@ thm_select_perm:: (Ord a) => l: List a -> x: a -> { permutation (Cons x l) (Cons (fst1 (select x l)) (snd1 (select x l ))) }  @-}
thm_select_perm:: (Ord a) => List a -> a -> Proof
thm_select_perm Nil x         
            =   permutation (Cons x Nil) (Cons (fst1 (select x Nil)) (snd1 (select x Nil )))
            ==. permutation (Cons x Nil) (Cons (fst1 (select x Nil)) (snd1 (select x Nil )))
            ==. permutation (Cons x Nil) (Cons (fst1 (x, Nil)) (snd1 (x, Nil )))
            ==. permutation (Cons x Nil) (Cons x Nil)     ? thmPermProp1 (Cons x Nil)
            ==. True                                    
            *** QED

thm_select_perm (Cons y ys) x = trivial

But same error occurs, why is that ??

**Comment by ranjitjhala** [comment] 2018-05-08 23:32
Hi @CodePeters -- can you paste the exact file (e.g. in a gist?) I wonder if you are missing some options e.g. did you run with `{-@ LIQUID "--reflection" @-}` ? (o.w. am traveling, will try to get back to you in a couple of days!)

**Comment by nikivazou** [comment] 2018-05-09 01:59
@CodePeters here is your solved file: http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1525830920_25472.hs

1.  To prove `permutation xs xs` you actually need to unfold the definition of `permutation xs xs` on `xs` and `xs`, which happens by calling  this as a Haskell  function (@ranjitjhala ple does not do the job here). 

2. The theorem `thm_select_perm` is proved for the `Nil` case, it is just that the location of the error is off. To leave the `Cons` case for later, just write `undefined` for the `Cons` case, as I did in the demo file above.

**Comment by ranjitjhala** [comment] 2018-05-09 07:28
Thanks @niki!  why was the original code not failing at some local `==.` ?

**Comment by CodePeters** [comment] 2018-05-09 08:36
Thanks @niki and @ranjitjhala for the replies.

Though I have some questions:

1) @nikivazou you mentioned that in order to prove `permutation xs xs` we have to write `permutation xs xs`  and this automatically unfolds. But why not do this by induction?? Induction seemed to work fine for this theorem...

2) Even if I tried to use undefined for `Cons` case this didn't seem to work, same error occurs again in `Nil` case. The version you linked works but you were using your own defined tuples, when I switched to this version it worked but my question is why the problem was the built in tuples ??

**Comment by facundominguez** [comment] 2024-06-03 22:45
Closing since I cannot reproduce this with built in tuples. The example I tried follows.

I'm not understanding the conversation on `permutation`, but I'm happy to engage into that if someone cares still.


```haskell
{-@ LIQUID "--reflection" @-}
{-@ LIQUID "--scrape-internals" @-}

module Test where

import qualified Data.Set as S

import Language.Haskell.Liquid.ProofCombinators

data List a = Nil | Cons a (List a)
{-@ data List [llen] @-}


{-@ measure llen @-}
{-@ llen :: List a -> Nat @-}
llen :: List a -> Int 
llen Nil = 0 
llen (Cons _ xs) = 1 + llen xs 


type Pair a b = (a, b )
{-@ measure snd1 @-}
snd1 :: Pair a b -> b 
snd1 (_, x) = x

{-@ measure fst1 @-}
fst1 :: Pair a b -> a 
fst1 (x, _) = x


{-@ measure lElems @-}
lElems :: (Ord a) => List a -> S.Set a
lElems Nil = S.empty
lElems (Cons x xs) = S.union (S.singleton x) (lElems xs)




{-@ reflect permutation @-}
permutation :: (Ord a) => List a -> List a -> Bool
permutation xs ys = lElems xs == lElems ys



{-@ reflect select @-}
{-@ select :: (Ord a) => a -> l1: List a 
           -> Pair a ({l2:List a | llen l2 == llen l1 } ) @-}
select :: (Ord a) => a -> List a -> Pair a (List a)
select i Nil = (i,  Nil)
select i (Cons x xs) 
  | i <= x    = let (j2, l2) = select i xs in (j2, Cons x l2)
  | otherwise = let (j1, l1) = (select x xs) in (j1, (Cons i l1))
        

selSort :: (Ord a) => List a -> List a
selSort Nil = Nil
selSort (Cons x xs) = (Cons j (selSort l))
  where (j, l) = (select x xs)

{-@ thmPermProp1 :: xs:_ -> {permutation xs xs} @-}
thmPermProp1:: (Ord a) => List a -> Proof
thmPermProp1 xs = permutation xs xs *** QED 

{-@ thm_select_perm:: (Ord a) => l: List a -> x: a -> { permutation (Cons x l) (Cons (fst1 (select x l)) (snd1 (select x l ))) } @-}
thm_select_perm:: (Ord a) => List a -> a -> Proof
thm_select_perm Nil x
  =   permutation (Cons x Nil) (Cons (fst1 (select x Nil)) (snd1 (select x Nil )))
  ==. permutation (Cons x Nil) (Cons (fst1 (select x Nil)) (snd1 (select x Nil )))
  ==. permutation (Cons x Nil) (Cons (fst1 (x, Nil)) (snd1 (x, Nil)))
  ==. permutation (Cons x Nil) (Cons x Nil)
  ==. True
  *** QED
thm_select_perm (Cons y ys) x 
  = undefined 
```

**Closed as completed by facundominguez** 2024-06-03 22:45 UTC
