### ISSUE TITLE
Meaningless error message: "altToLg on Default"

### ISSUE THREAD

**Issue by awstlaur** [ucsd-progsys/liquidhaskell#890] opened 2016-12-09 18:28 UTC
```haskell
{-@ reflect cycleTakeHelper @-}
cycleTakeHelper :: [a] -> [a] -> Int -> [a]
cycleTakeHelper _ _ 0         = []
cycleTakeHelper full [] n     = cycleTakeHelper full full n
cycleTakeHelper full (x:xs) n = x : (cycleTakeHelper full xs (n - 1))
```
Example program above, error below. 
```
**** RESULT: ERROR *************************************************************


 <no location info>: Error: Uh oh.
BadErrorMsg.hs:1:13: Error: Cannot promote Haskell function cycleTakeHelper to logic
    altToLg on Default
```

For the curious, I'm trying to simulate taking a finite prefix of an infinite list without explicitly evoking an infinite list, because Liquid Haskell seems to have trouble with those in general. I wanted to `reflect` this in order to prove things about the functions that depend on it. 

(Even with the `--no-termination` flag, this error still shows up.)

**Comment by ranjitjhala** [comment] 2016-12-09 19:36
Not sure whats happening above -- probably hit a bug in the "promoting" code, 

but see this for an example of how to represent infinite lists, and also "take" values from them:

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/docs/slides/BOS14/hs/end/04_Streams.hs

**Comment by awstlaur** [comment] 2016-12-09 21:59
@ranjitjhala Thanks so much for pointing out that file! I was able extend it to write [exactly what I wanted](https://github.com/awstlaur/LiquidHaskellExamples/blob/45cad2e9c1ce35e00b8677b5d980057adec5f5d4/Streams.hs).

**Comment by ranjitjhala** [comment] 2016-12-09 22:41
Great! Will leave this open till we have fixed it (or give a better error message!)

**Comment by edsko** [comment] 2017-11-06 15:59
I think this is a duplicate of  https://github.com/ucsd-progsys/liquidhaskell/issues/941 (note that OP's code is doing a similar style match on `Int` in the third argument).

**Comment by nikivazou** [comment] 2017-11-06 18:10
Thanks @edsko. I actually recently updated this error message. Should I close the issues after the following commit?

https://github.com/ucsd-progsys/liquidhaskell/commit/b1299b54c596f4eee427ac24ef11e8ed94144186

**Comment by edsko** [comment] 2017-11-07 15:06
@nikivazou Yes, the new error message is much clearer.

**Closed** 2017-11-08 03:36 UTC

**Comment by awstlaur** [comment] 2017-11-08 03:43
Glad to see this got a better error message!

One nitpick, however: the message contains "Make sure **you** function is..."; the **you** should probably either be **your** or **the**

**Comment by nikivazou** [comment] 2017-11-08 03:46
Thanks! I did catch this error just after pushing so it is in the next commit.

**Comment by ranjitjhala** [comment] 2017-11-08 05:35
Thanks @nikivazou and @awstlaur !
